### ISSUE TITLE
http-bind/ ws-xmpp works initially but after a while stops working

### ISSUE THREAD

**Issue by andrewvmail** [esl/MongooseIM#1045]
I'm using b13807d Merge pull request #577 from esl/muc_light

I'm using strophejs to connect to MongooseIM. I used ws-xmpp and also http-bind.
able to get it to work but after a few minutes strophe just stopped working. 
Was able to receiving incoming stanza from another users for a few minutes.

On websocket. I still see the ws connections in chrome network tools except its not receiving anything thing. 

ON http-bind after a while I get 

```
XMLHttpRequest cannot load http://kakawterraw.com:5285/http-bind. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://175.25.50.106:8100' is therefore not allowed access. 
Strophe failed to connect.
```

Just before that strophe posted to http://kakawterraw.com:5285/http-bind

```
<body rid='3848827848' xmlns='http://jabber.org/protocol/httpbind' sid='c16834eb2479b8f42cccad0e1f810ed25848882f'/>
```

and mongoose returns 

```
HTTP/1.1 200 OK
server: Cowboy
date: Fri, 21 Oct 2016 00:06:22 GMT
content-length: 0
```

I noticed all response from mongoose prior to that all have Access-Control-Allow-Origin:\* . Not sure why that particular one does not ... I think its tripping out the browser because of that

Any ideas?

Thanks in advance

A

**Comment by andrewvmail** [comment]
Another note if I replay the same request it returns 

```
HTTP/1.1 200 OK
server: Cowboy
date: Fri, 21 Oct 2016 00:43:28 GMT
content-length: 95
content-type: text/xml; charset=utf8
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: POST, OPTIONS, GET
Access-Control-Allow-Headers: Content-Type
Access-Control-Max-Age: 1728000
```

**Comment by andrewvmail** [comment]
I think related to #1150

**Comment by Zatvobor** [comment]
I did quick fix, here https://github.com/Zatvobor/MongooseIM/commit/ab5d43305c77bb1fb206825ae3f49a68284de632

**Comment by michalwski** [comment]
Hi @andrewvmail and @Zatvobor 

Thanks for your contributions. I somehow missed the issue.

The quick fix provided by @Zatvobor is valid, would you mind sending a PR to master branch?

**Comment by Zatvobor** [comment]
Sure. Which one branch should be used for the PR?
Thanks.

**Comment by michalwski** [comment]
master branch :)

**Comment by LeartS** [comment]
Could be useful for others coming here: I had the same problem and it turned out to be a combination of client "error" and server parameters.

After I while I found out that the cause was my client did not respond to pings, neither with [pongs or service-unavailable](https://xmpp.org/extensions/xep-0199.html#s2c) and the server was configured with `mod_ping` with `timeout_action` `kill`, which means the server kills the connection if it doesn't receive a reply to pings in a certain amount of time (in my case, 30 seconds).

That's why the client would stop working with both websockets or BOSH. In the case of BOSH, the problem could be misattributed to a CORS problem because once the server has killed the connection the client doesn't know and tries to send its next request normally. The server replies with an empty response (it doesn't have even CORS headers), and the browser raises a CORS error, but the problem had already happened (the server killed the connection). The CORS error is a symptom, not the cause.
