### ISSUE TITLE
How to enable/test SSL on MongooseIM chat server over Transport layer.

### ISSUE THREAD

**Issue by vickydhas** [esl/MongooseIM#1051]
MongooseIM version: MongooseIM version 2.0.0beta2-312-g3cec442
Installed from: Github cloned url
Erlang/OTP version: `Erlang/OTP 18 [erts-7.3] [source] [64-bit] [async-threads:10] [kernel-poll:false]`

Describe the issue.
Its not an issue but a query, sorry for being a newbie but this github have helped me to learn a lot and innovate things. Thanks to Michal always.

1) I am looking to enable the SSL encription for the XMPP Chat that is setup with this MongooseIM server.
2) I see there is in mongooseim/priv/ssl/fake_(server,cert,ket) files already in for the SSL handling
3) I have also checked the ejabberd.cfg file that have SSL enabled with these keys path mentioned.

How to test and check with out actual server and what all are needed from the administration to setup the SSL on this chat medium on transport layer.

Any guidance is much appreciated.

**Comment by michalwski** [comment]
TLS is enabled by default by with self-signed fake certs. You need to change them to real certificates if you want to smoothly support TLS from different client libraries. More info can be found here: http://mongooseim.readthedocs.io/en/latest/Advanced-configuration/#configuring-tls-certificates-keys

In order to test the TLS support I recommend `openssl s_client`. It even allows you to use STARTTLS which is the usual method of using TLS with XMPP.
