### ISSUE TITLE
Build MongooseIM 2.0 from source failed in Mac OSX

### ISSUE THREAD

**Issue by chinhniem80** [esl/MongooseIM#1199]
MongooseIM version: 2.0
Installed from: source
Erlang/OTP version: Erlang/OTP 18 [erts-7.3] [source-d2a6d81] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false]

Mac OSX: El Capitan, version 10.11.6
After get the code from https://github.com/esl/MongooseIM/ branch bind-2.0
Goto MongooseIM-bind-2.0 folder, do 'make': 

=========================
...
===> Compiling re2
Cloning into 're2'...
fatal: remote error: 

Invalid authentication credentials.

Please generate a new identifier:
  https://code.googlesource.com/new-password

===> Hook for {pc,compile} failed!

make: *** [rel] Error 1
=========================

I tried to install re2 (using brew install re2), then copy the source again, and 'make', but the error was the same. What will I do with this?
Thank you,

**Comment by michalwski** [comment]
Hi @chinhniem80,

Thanks for rising the issue. I see you are interested in bind-2.0 branch (implementing [XEP-0386: Bind 2.0](https://xmpp.org/extensions/xep-0386.html)). This is still work in progress and any feedback is more then welcome.

Your issue looks like sth very specific to re2 which is one of our deps, I've never run into this problem so far. I recommend downloading and building re2 from https://github.com/tuncer/re2 so that you can verify if this works if used directly. Let me know about the outcome.

**Comment by chinhniem80** [comment]
Hi Michalwshi,
I tried to install re2 on Mac OS X, but the outcome was the same. I put the question on re2 github.
Thank you.
