### ISSUE TITLE
if c2s fails to send message while opening session it crashes in a weird place

### ISSUE THREAD

**Issue by bartekgorny** [esl/MongooseIM#1252]
The sequence is the following: we are in `wait_for_session_or_sm` state, we receive a stanza. The function  [`send_and_maybe_buffer_stanza/3`](https://github.com/esl/MongooseIM/blob/6507675174a8f254cbc2e65fbc78cf240c5c2c8f/apps/ejabberd/src/ejabberd_c2s.erl#L1611), if everything goes right, returns `fsm_next_state/2` which is a four-item tuple. But, if anything goes wrong, it returns [`maybe_enter_resume_session/2`](https://github.com/esl/MongooseIM/blob/6507675174a8f254cbc2e65fbc78cf240c5c2c8f/apps/ejabberd/src/ejabberd_c2s.erl#L2851), which returns a three-element tuple because `stream_mgmt_it` is `undefined`. Thus, c2s crashes at [`do_open_session/3](https://github.com/esl/MongooseIM/blob/6507675174a8f254cbc2e65fbc78cf240c5c2c8f/apps/ejabberd/src/ejabberd_c2s.erl#L814) because "no match on the right side". I guess it could be improved, one way or another. Not sure how to write a regression test for it, though.

**Comment by michalwski** [comment]
Good catch! It has to be improved!

In order to write a regression test you would need to:
1. Move the c2s to `wait_for_session_or_sm` state (this can be easily done with `escalus` and custom steps to the connection)
2. Mock `mongoose_transport:send_xml` function to return a error.

The perfect place for this regression test is, IMO, `ejabberd_c2s_SUITE.erl` in small tests. You don't have escalus there, nor running MongooseIM, so it'll be harder to have the c2s process in a desired state.
