### ISSUE TITLE
Can't allow users to change their password

### ISSUE THREAD

**Issue by FlorentCoppint** [esl/MongooseIM#1268]
MongooseIM version: 2.0.1
Installed from: .deb package
Erlang/OTP version: 19.3-1

Hi,
I can't find the right configuration to allow registered users to change themselves their password, and in the same time, disallow in-band registration for new users.
My configuration is : 

{access, register, [{deny, all}]}.

{mod_register, [
		  {welcome_message, {""}},
		  {ip_access, [{allow, "0.0.0.0/0"}]},
		  {access, register}
		 ]}

That's what I found in ejabberd/mongooseim doc, but I always get a "403 Forbidden" when I want to change my password from Pidgin.

What did I miss ?

Thank you

**Comment by fenek** [comment]
Hi @FlorentCoppint 

Unfortunately it is not possible with current implementation, since both password change and registration logic both use the same Access Control List. So either both are enabled or both disabled.

On the other hand, it would be very easy to change it. If you know Erlang, you can do it on your own and submit a patch, or wait for our open source team to implement this improvement. :)

**Comment by vickydhas** [comment]
Hi @FlorentCoppint  You can use the HTTP Swagger API feature of MongooseIM that can allow you to change the password for the particular user. 

Or else use the register user XEP to modify the password (condition: the user have to be connected first with old password and then just send change password XEP as given below, it worked for me on both cases.)

Reference : [Swagger Usermanagement --> PUT request section](https://mongooseim.readthedocs.io/en/latest/swagger/index.html#/)

Using XEP from client already connected: 

    //    <iq xmlns="jabber:client" id="agsXMPP_5" type="set" to="gsrv"><query xmlns="jabber:iq:register"><username>test</username><password>test321</password></query></iq>
