### ISSUE TITLE
can we use minio with mongoseIM for s3 storage. (mod_http_upload)

### ISSUE THREAD

**Issue by Mo33n** [esl/MongooseIM#1392]
MongooseIM version: (put the version)
Installed from: (source or pkg)
Erlang/OTP version: (put the version)

Describe the issue.
Its more likely a question.

**Comment by kzemek** [comment]
Hi @Mo33n ,

It doesn't work on the current master version, because Minio doesn't support ACLs and don't take them into account when calculating signatures. I pushed some changes in https://github.com/esl/MongooseIM/pull/1415 , and on that branch the S3 backend works with with `play.mimio.io` using the following config:

```erlang
{mod_http_upload, [
  {backend, s3},
  {expiration_time, 600}, % play.mimio.io's clock is skewed by few minutes
  {s3, [
        {bucket_url, "https://play.minio.io:9000/bucket"},
        {add_acl, false},
        {region, "us-east-1"},
        {access_key_id, "Q3AM3UQ867SPQQA43P2F"},
        {secret_access_key, "zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG"}
  ]}
]},
```

**Comment by Mo33n** [comment]
Thanks , Waiting for the merge.

**Comment by shaljam** [comment]
Does MongooseIM `2.2.2` work with minio? I can't get it to work.
