### ISSUE TITLE
mod_privacy update list broadcast handling

### ISSUE THREAD

**Issue by jonasrichard** [esl/MongooseIM#1421]
MongooseIM version: 1.6
Installed from: source
Erlang/OTP version: 18.3

I don't know if it is an issue or misuse of the protocol, or shortage of the protocol. Let us discuss it.

**Steps to reproduce.** Ensure that the user doesn't have default privacy list and any of its privacy list doesn't contain any jid. Login with the user A and user B. User A blocks user B, but user B can send messages to user A. I don't know if it happens only when user B logs in via websocket, but according to the source code, it should be independent.

**What happens?** In the c2s state the current privacy list of the user is cached. In default its name is 'none' because there is no default privacy list. Let us select a privacy list called "public". It fails because there is no such privacy list yet. Let us then block a user, by `local1@localhost` sending

```
<iq type='set'>
<query xmlns='jabber:iq:privacy'>
<list name='public'>
<item type='jid' order='1' action='deny' value='local2@localhost'/>
</list>
</query>
</iq>
```

The privacy list change is broadcasted, and [the c2s](https://github.com/esl/MongooseIM/blob/fdb70428389f6771582b00356747c839fdcff103/apps/ejabberd/src/ejabberd_c2s.erl#L1379) handles this change. In the end it calls the [mod privacy updated list function](https://github.com/esl/MongooseIM/blob/fdb70428389f6771582b00356747c839fdcff103/apps/ejabberd/src/mod_privacy.erl#L429) which supposed to update the list in the c2s state.

The problem - and also the correct behaviour - is to update the cached list only if is the current/default list which has been changed. But in our case the list is 'none', so it doesn't update the internal state of c2s.

The bigger problem is if I want to fix the situation, I send a

```
<iq type='set'>
<query xmlns='jabber:iq:privacy'>
<list default='public'/>
</query>
</iq>
```

but it doesn't send a broadcast, so the blocked `local2` user still can send me commands. Let us note that I cannot send this command successfully when the privacy list doesn't exist.

Since I use only one privacy list, I updated this function to

```
updated_list(_, #userlist{name = none}, New) ->
    New;
updated_list(_, #userlist{name = OldName} = Old, #userlist{name = NewName} = New)
        when OldName =:= NewName ->
    New;
updated_list(_, Old, _) ->
    Old.
```

because in our special use-case it works. But I don't know how the protocol & MongooseIM should handle this situation (aka selecting the default list and block the first user).

**Comment by fenek** [comment]
Hi @jonasrichard 

Indeed it would be very handy if the Privacy Lists specification had a mechanism to automatically enable new privacy list when none is active at the moment. Unfortunately, MongooseIM must follow the XEP and the extension does not specify that updating/creating a list should make it active under some circumstances.

On the other hand, Privacy Lists XEP requires the server to apply the default list to the current user sessions that do not have any lists activated and by looking at the code, MongooseIM might actually not ensure this and there is not test case for it.

Thank you for the report then. In order to be compliant with the standard, we cannot automatically activate the newly submitted list but we should definitely automatically activate the new default list (if none is active for the session). Someone will investigate that but I'm not sure where will it fit in our roadmap.

Have you considered using `mod_blocking`? For simple user blocking would work perfectly and would spare you the headache with multiple, default or active lists.
