### ISSUE TITLE
Question on clustering

### ISSUE THREAD

**Issue by acelabs88** [esl/MongooseIM#1460]
MongooseIM version: (2.1.0beta2)
Installed from: (docker)
Erlang/OTP version: (not sure how to get this info)

I am trying to set up the clustering support. I have two basic questions:

1. For all the nodes within the same cluster, should I configure them with the same storage server? E.g. in my case I am using mysql, does it mean I need to configure all nodes to use the same database of the same mysql server?

2. Is it recommended to set up nodes for the same cluster in different geolocations? E.g. one node in US and another node in Asia? Or should I resort to federation in this case?

Please let me know if this is not the right forum for asking such questions. Thanks!

**Comment by jonasrichard** [comment]
I just see this question but I also use Mongoose and I can answer them.

1. You should use the same database. Since users can connect to any not of the cluster randomly, the data partitioning is not an option (when one cluster node sees only some part of the whole data, messages, user profiles, etc).

2. It is a generic Erlang question. The answer is no, the cluster communication works in LAN networks for performance and stability (and security) reasons. In general if the traffic is high, Erlang can provide low-latency responses, but it requires that the network between the nodes have low-latency as well (local network).

**Comment by fenek** [comment]
@acelabs88 

Are the answers provided by jonasrichard sufficient for you? :) If not, what would you like to know?

If yes, can you please close the ticket?

**Comment by acelabs88** [comment]
Thanks for the answer. That helped a lot. Sorry for the delay in closing as for some reason I missed the github notification for this.
