### ISSUE TITLE
We observed , If a deviceId for Push notification is changed for a particular device. MongooseIM doesn't override the deviceId

### ISSUE THREAD

**Issue by Mo33n** [esl/MongooseIM#1525]
MongooseIM version: 20.1
Installed from:source
Erlang/OTP version: 19

Describe the issue.

We observed , If a deviceId for Push notification is changed for a particular device. MongooseIM doesn't override the deviceId.

But it try to send the notification on all the previous deviceId for that user. in that case we see alot of deviceId invalid errors on mongoosePush logs.

**Comment by rslota** [comment]
Hi @Mo33n ,

In order to confirm the issue, I need more details. Namely: `BareJID` and `Node` from the `enable` stanza send by client. 
The standard (XEP-0357), states that if you send `enable` stanza with different `BareJID` or `Node`, it should be treated as additional device for publishing. I you wish to override the device you `MUST` use the same `BareJID` or `Node`. If you want to use new `Node` for the same device, you `MUST` send `disable` stanza from the client with the old `Node` value beforehand.

**Comment by Mo33n** [comment]
@rslota  Thank Now , i understand the exact case,
I was creating new node , and not disabling old one.
