### ISSUE TITLE
OTP Compatibility

### ISSUE THREAD

**Issue by GalaxyGorilla** [esl/MongooseIM#1544]
Since release 2.1.0 MIM is at least partially not compatible anymore with the [OTP principles](http://erlang.org/doc/design_principles/applications.html) because there is no `.app.src` file anymore. Well, in fact there seems to be not even a `mongooseim` application anymore. The current state makes it rather difficult to use MIM as a dependency without some hacking. To my understanding one of the main goals of MIM was always to stay in that compatibility (as an enhancement to `ejabberd`) so the steps taken here are kind of baffling to me. What is going on here?

**Comment by michalwski** [comment]
This issue is related to moving from `rebar` to `rebar3`. We decided to start building the project with `rebar3` as more and more deps were working only with `rebar3`.

MongooseIM is an umbrella project still (see the `apps` dir), not single application. We had to remove the main `mongooseim.app.src` file in order to be able to use `rebar3` to build and test the project. `rebar3` (back then) was simply not able to work with the `umbrella` structure if there was `src` dir with `.app` file in the project's root.

I see it's important for you @GalaxyGorilla and @sstrigler to be able to use MongooseIM as a dependency. Before releasing `2.1.0` we had 2 beta versions where the change was also included. I wish we had gotten your feedback back then. We would have chance to improve final `2.1.0` relase according to your feedback. 

One of the ways in which the issue can be fixed is transforming MongooseIM to a proper application and not an umbrella project. This (to me) means moving everything from `apps/ejabberd/src` into `src` and removing `ejabberd` application in favour of `mongooseim` application. Would that work for you @GalaxyGorilla and @sstrigler? We are open to other suggestions as well.

**Comment by GalaxyGorilla** [comment]
Hey @michalslaski, you're absolutely right, we should've noticed this before the release. Unfortunately updating a MIM version is not really a free lunch for me and so testing the new release was postponed to the actual release (big shame on me). However, I would not have expected such a dramatic change (which is not even noted in any changelog?).

I don't now the diff between upstream ejabberd and MIM well, so for me the question is also if MIM wants to be a soft fork of ejabberd or an "independent" application. If it is the latter one (which I believe it is) then I personally would expect there to be a `mongooseim` application (and not `ejabberd`). So your proposal sounds totally reasonable to me :).

**Comment by sstrigler** [comment]
I think moving `apps/ejabberd` to just `src` is overdue, what's ejabberd anyway? 😜

**Comment by fenek** [comment]
@GalaxyGorilla @sstrigler 

We're definitely going to fix it, I hope it will happen late Nov./early Dec. :)

**Comment by sstrigler** [comment]
Thanks a lot already!

**Comment by fenek** [comment]
@sstrigler 

We'll begin fixing the issue this week. :)

**Comment by fenek** [comment]
@sstrigler Can you please check if it works for you now? :)

**Comment by sstrigler** [comment]
@GalaxyGorilla on it already :)

**Comment by GalaxyGorilla** [comment]
I updated to current master and and everything seems to be fine :). Thanks a lot for the support and especially for all the work put into #1580 by @arkgil !

**Comment by arkgil** [comment]
Glad to hear that, @GalaxyGorilla ! 🎉
