### ISSUE TITLE
Is 2.1.0beta2 production-ready?

### ISSUE THREAD

**Issue by jonathanve** [esl/MongooseIM#1549]
MongooseIM version: 2.1.0beta2

Hello, @fenek . Hope you're OK. We have been using MongooseIM 2.1.0beta2 with some custom erlang code. Everything's worked so far. We see your team just released version 2.1.0. Do you guys recommend switching to 2.1.0 or is 2.1.0beta2 production-ready?

Thanks!

**Comment by fenek** [comment]
Hi @jonathanve 

I definitely recommend switching to the current stable version. :) Please bear in mind that 2.1.0 final does not only introduce more features (since beta2) but also features some important improvements (MAM 0.6 support, better MAM ID generation...) and fixes (correct RDBMS backoff calculation, URL processing in `mod_http_upload`).

I'm not sure how extensive your customisations are but the only significant internal change in this iteration is the final stage of "Mongoose accumulators". If it conflicts with your code somehow, well... you'll need to adjust it at some point anyway, even if you wait a bit with update (e.g. until 2.1.1).

**Comment by jonathanve** [comment]
thanks @fenek ! Looking forward for 2.1.1 as well. And you're right, at some point we will have to do the migration anyway.
