### ISSUE TITLE
MongooseIM crashes while implementing push notification

### ISSUE THREAD

**Issue by sandy5487** [esl/MongooseIM#1690]
MongooseIM version: 2.1.0
Installed from: source
Erlang/OTP version: 20

MongooseIM crashes while implementing push notification.

Crash logs:
```

Slogan: Problem starting the module mod_event_pusher_push for host <<"localhost">>
 options: [{wpool,[{workers,100}]}]
 error: undef
[{mod_event_pusher_push,start,[<<"localhost">>,[{wpool,[{workers,100}]}]],
System version: Erlang/OTP 19 [erts-8.3.5] [source] [64-bit] [async-threads:5] [hipe] [kernel-poll:true]
```

here is the configuration:

```
 {mod_event_pusher, [
    {backends, [
        {push, [
            {backend, odbc},
            {wpool, [{workers, 100}]},
            {plugin_module, mod_event_pusher_push_plugin_defaults}
        ]}
    ]}
 ]},

{mod_pubsub, [
    {plugins, [<<"push">>]}
 ]},

 {http_connections, [{mongoose_push_http,
    [{server, "https://localhost:8443"}]
 }]},

 {mod_push_service_mongoosepush, [
    {pool_name, mongoose_push_http},
    {api_version, "v2"}
 ]}
```

**Comment by fenek** [comment]
Have you tried using this config with clean build? Lack of `mod_event_pusher_push` with `mod_event_pusher` being available doesn't make sense because they were added together in single update.

What is more, the error message doesn't correspond to the config file you've pasted. Error mentions push backend configured with `[{wpool,[{workers,100}]}]` but your config says `[{backend, odbc},
 {wpool, [{workers, 100}]}, {plugin_module, mod_event_pusher_push_plugin_defaults}]`.

BTW: Are sure you're using 2.1.0? Event Pusher has been added in 2.1.1.

**Comment by Beisenbek** [comment]
Hi @fenek 

In documentation I found the same config: 
https://github.com/esl/MongooseIM/blob/2.1.1/doc/modules/mod_event_pusher_push.md, which says:

in "Example configuration" section
{mod_event_pusher, [
    {backends, [
        {push, [
            {backend, mnesia},
            {wpool, [{workers, 200}]},
            {plugin_module, mod_event_pusher_push_plugin_default}
        ]}
    ]}
]}

**Comment by fenek** [comment]
@sandy5487 

How did you resolve your issue?

**Comment by sandy5487** [comment]
@fenek 
It was my fault I was using this block in modules:
```
{http_connections, [{mongoose_push_http,
    [{server, "https://localhost:8443"}]
 }]}
```
