### ISSUE TITLE
Add support for XEP-0256 (Last Activity in Presence)

### ISSUE THREAD

**Issue by Ghostw4lk** [esl/MongooseIM#1766]
MongooseIM version: 2.1.1
Installed from: Source
Erlang/OTP version: 20.0

This protocol allows to show other users the last online state (E.g.: Last seen, 10 minutes ago). Because with XEP-0012 (Last Activity) it is not possible to get the "real" presence state. In our chat app, we do not disconnect users, to support real time message delivery. So the user is always marked as "online". Only the server closes the connection, if the client is not reachable for a specific amount of time. Then the last activity is stated with the timeout date.

Is it possible to add this feature on the roadmap? That would be great. :)

Thanks in advance.

**Comment by GalaxyGorilla** [comment]
See #1474. I left a comment there which explains the situation AFAIK.

**Comment by Ghostw4lk** [comment]
If a client set the presence to "unavailable", then the server does not deliver messages to this client, rather the messages are saved to the offline message storage or MAM. Then the client has to check the message storage periodically and the messages does not get delivered in real time.

**Comment by GalaxyGorilla** [comment]
OK, I'm really not an XMPP expert but my thinking was that you go 'unavailable' when the client is not really using the connection (e.g. background mode) and then go 'available' again when needed (and then check the archive etc.). Always getting stuff delivered in real time sounds to me like heavy battery drain assuming that we are talking about mobile apps.

**Comment by fenek** [comment]
Hi @Ghostw4lk @GalaxyGorilla 

When a client sends `unavailable` presence, it does not prevent server completely from routing stanzas to this sessions. Every stanza addressed to a full JID will be delivered anyway.

I order to provide a behaviour you need, please use https://xmpp.org/extensions/xep-0352.html implemented as `mod_csi` in MongooseIM. It allows to switch session to "inactive" state where the server will buffer messages for the session until it becomes "active" again.

And finally, in order to answer the original question: XEP-0256 isn't in the roadmap currently. Issue #1474 on the other hand has a good chance of resolution until 3.0 release.

**Comment by GalaxyGorilla** [comment]
Ah thanks @fenek for clearing that up :)

Just our of curiosity: what do you do when the buffer is full? Use the archive anyway? I can imagine that this is a problem is groupchats.

**Comment by fenek** [comment]
In case of Stream Management buffer overflow, client session has limited time to process it. When it runs out, the session is considered unresponsive and closed.

In case of CSI "inactive" buffer overflow, the whole buffer is forcibly flushed and delivered to the client, despite "inactive" state. Session remains in this state so subsequent messages will be stored in buffer again.

**Comment by fenek** [comment]
@GalaxyGorilla @Ghostw4lk 

Any more questions on this topic or can we close the issue? :)

**Comment by Ghostw4lk** [comment]
@fenek Thank you very much for your reply. I will try to realize this with your suggestion (XEP-0352).
