### ISSUE TITLE
Unable to submit some push notifications

### ISSUE THREAD

**Issue by Beisenbek** [esl/MongooseIM#1772]
MongooseIM version: 2.1.1 
Installed from: source
Erlang/OTP version: 18

We're getting next sequence of warnings related to mod_push_service_mongoosepush.

`2018-03-15 05:48:14.120 [warning] <0.833.0>@mod_push_service_mongoosepush:http_notification:109 Unable to submit push notification. ErrorCode 404, Payload <<"{\"details\":\"This is not the endpoint you are looking for.\"}">>`

`2018-03-15 05:48:14.558 [warning] <0.748.0>@mod_push_service_mongoosepush:http_notification:109 Unable to submit push notification. ErrorCode 500, Payload <<"{\"details\":\"bad_device_token\"}">>`

`2018-03-15 05:48:14.940 [warning] <0.744.0>@mod_push_service_mongoosepush:http_notification:109 Unable to submit push notification. ErrorCode 500, Payload <<"{\"details\":\"invalid_device_token\"}">>`

`2018-03-15 05:48:14.949 [warning] <0.759.0>@mod_push_service_mongoosepush:http_notification:109 Unable to submit push notification. ErrorCode 500, Payload <<"{\"details\":\"invalid_device_token\"}">>`

`2018-03-15 05:48:15.037 [warning] <0.734.0>@mod_push_service_mongoosepush:http_notification:109 Unable to submit push notification. ErrorCode 500, Payload <<"{\"details\":\"unregistered\"}">>`

`2018-03-15 05:48:15.063 [warning] <0.743.0>@mod_push_service_mongoosepush:http_notification:109 Unable to submit push notification. ErrorCode 500, Payload <<"{\"details\":\"invalid_device_token\"}">>`

As I understand, after some period of time fcm or apns tokens are expired. An MongooseIM confused with the old token. Is it possible to make workaround with it. Or this problem more related to [MongoosePush](https://github.com/esl/MongoosePush)?

**Comment by fenek** [comment]
Can you please share your `mod_push_service_mongoosepush` configuration? :)

**Comment by Beisenbek** [comment]
Sure,

1. `  {mod_push_service_mongoosepush, [
      {pool_name, mongoose_push_http},
      {api_version, "v2"}
  ]}
`

2. `{http_connections, [{mongoose_push_http,
    [{server, "https://push.chat.com"}]
}]}`

3. `{mod_event_pusher, [
    {backends, [
        {push, [
            {backend, mnesia},
            {wpool, [{workers, 200}]},
            {plugin_module, mod_event_pusher_push_plugin_defaults}
        ]}
    ]}
  ]}
`

4. `  {mod_ping, [{send_pings, true},
      {ping_interval,40},
      {timeout_action,kill},
      {ping_req_timeout,20}]}
`



5. `{mod_pubsub, [  
               {plugins, [<<"push">>]}
  ]}
`

**Comment by fenek** [comment]
It seems that out of all these logs the only one really worrying is:

`2018-03-15 05:48:14.120 [warning] <0.833.0>@mod_push_service_mongoosepush:http_notification:109 Unable to submit push notification. ErrorCode 404, Payload <<"{\"details\":\"This is not the endpoint you are looking for.\"}">>`

This indeed will have to be investigated. @rslota Can you recommend something?

For the remaining ones - the client devices are supposed to update their tokens when they expire. If they do - are you using the same pubsub node name for these updates?

**Comment by rslota** [comment]
@fenek The current code base doesn't log the URL used to make a request which is very unfortunate. Because of that I can see only two options (MongooseIM related): Either trace arguments of `mod_push_service_mongoosepush:http_notification/5` or change log message in this function. 
I've prepared PR with slightly improved logging on MongooseIM side: #1777.

@Beisenbek Each `enable` stanza (see XEP-0357) from the same client device should use the same pubsub's `node`. This way, new device token will override the old one. If there is need to change pubsub `node` for the device for some reason, device shall send explicit deactivation via `disable` stanza (also XEP-0357). If the device sends new token with new `node` ID, both will be used and one of them will be failing every single time until disabled. 
In future I plan to modify MongoosePush / MongooseIM to make it possible to use synchronous push sending in order to let MongooseIM to automatically disable expired device tokens. This will not however fix any of those issues, since the client device still needs to provide a new one. This will only reduce number of warnings in MongooseIM logs.

**Comment by fenek** [comment]
@Beisenbek Can you please try to reproduce the problem with `handle_mongoosepush_errors` branch?

**Comment by Beisenbek** [comment]
@fenek @rslota is it possible to update the `mongooseim pubsub node` about APNs/FCM token change when app is not running? Is there any way to handle this scenario before user launches the app?

**Comment by Beisenbek** [comment]
Hi @fenek 

I reproduced the problem with `handle_mongoosepush_errors` branch. Logs:

`2018-04-06 12:55:05.408 [error] <0.1152.0>@mod_push_service_mongoosepush:http_notification:109 Unable to submit push notification. ErrorCode 404, Payload <<"{\"topic\":\"{host}.voip\",\"service\":\"apns\",\"mode\":\"prod\",\"data\":{\"message-count\":1,\"last-message-sender\":\"UserA@{host}}\",\"last-message-body\":\"test1\"}}">>.Possible API mismatch - tried URL: <<"v2/notification/">>.`

`2018-04-06 12:55:07.045 [error] <0.1152.0>@mod_push_service_mongoosepush:http_notification:109 Unable to submit push notification. ErrorCode 404, Payload <<"{\"topic\":\"{host}}.voip\",\"service\":\"apns\",\"mode\":\"prod\",\"data\":{\"message-count\":1,\"last-message-sender\":\"UserA@{host}}\",\"last-message-body\":\"test2\"}}">>.Possible API mismatch - tried URL: <<"v2/notification/">>.`

**Comment by fenek** [comment]
@rslota Can you please take a look?

**Comment by rslota** [comment]
@fenek @Beisenbek The device token is empty. 
It should be provided in `enable` stanza as `device_id` option. Right now, from what I can see, there is only validation that checks whether this option exists, MongooseIM doesn't check whether it's non-empty. Therefore, as in this case, empty string used as device token which ends up calling invalid endpoint on MongoosePush (since device token is a part of URL),

**Comment by Beisenbek** [comment]
Thank you for information. Sure we're sending `device_id` in following stanza:
```<iq type='set' id='x43'>
  <enable xmlns='urn:xmpp:push:0' jid='pubsub.mypubsub.com' node='punsub_node_for_my_private_iphone'>
    <x xmlns='jabber:x:data' type='submit'>
      <field var='FORM_TYPE'><value>http://jabber.org/protocol/pubsub#publish-options</value></field>
      <field var='service'><value>apns</value></field>
      <field var='device_id'><value>your_pns_device_token</value></field>
      <field var='silent'><value>false</value></field>
      <field var='topic'><value>some_apns_topic</value></field>
    </x>
  </enable>
</iq>
```
I'm wondering why sometimes device_id is empty. I'll look for error in mobile client code.
