### ISSUE TITLE
Introducing new hooking library

### ISSUE THREAD

**Issue by Pouriya-Jahanbakhsh** [esl/MongooseIM#1865]
Hi. I just wrote new hooking library [**posthaste**](https://github.com/pouriya-jahanbakhsh/posthaste). Its API is more like `ejabberd_hooks` API and functionality. But in lookup operation (for large number of processes at the same time) it's about 3-5 times faster than ETS. Do you want to look at that or use that ? If yes, i can open a pr.
thanks

**Comment by ludwikbukowski** [comment]
Hi @Pouriya-Jahanbakhsh, sounds interesting :)
Correct me if I'm wrong, but your library doesn't support functions like `ejabberd_hooks:run/3` or `ejabberd_hooks:run_fold/4` but it's more like callbacks' storage?

**Comment by Pouriya-Jahanbakhsh** [comment]
You're right, it doesn't. It just supports add/delete operations and gives callbacks and information (hooks, keys, number of callbacks for each key). In `ejabberd_hooks` instead of getting hooks from ETS we can get them from `posthaste`.  
```erlang

%% Current code:
run_fold(Hook, Host, Val, Args) ->
    Res = case ets:lookup(hooks, {Hook, Host}) of
        [{_, Ls}] ->
            mongoose_metrics:increment_generic_hook_metric(Host, Hook),
            run_fold1(Ls, Hook, Val, Args);
        [] ->
            Val
     end,
    record(Hook, Res).

%% Using posthaste:
run_fold(Hook, Host, Val, Args) ->
    Res = case posthaste:callbacks(hooks, Hook, Host) of
        [] ->
            Val;
        Ls ->
            mongoose_metrics:increment_generic_hook_metric(Host, Hook),
            run_fold1(Ls, Hook, Val, Args)
    end,
    record(Hook, Res).
```

**Comment by GalaxyGorilla** [comment]
Hey @Pouriya-Jahanbakhsh, I had no real look into your code so far but can you provide any hard numbers (e.g. average microseconds of a lookup or whatever) compared with the current code? The thing is that an improvement of a few microseconds in a call which actually needs 20 milliseconds is somewhat neglectable IMHO and settles in the end just further maintenance burden (ets is pretty stable stuff :P).

**Comment by Pouriya-Jahanbakhsh** [comment]
@GalaxyGorilla hey you ! I agree with ETS stablity compared with my code. You just have to clone it and export `ERL_POSTHASTE_BENCHMARK=1` and run `rebar3 ct`. It has creation and lookup benchmark for borh ETS and itself. In lookup benchmark (if i remember my last edition correctly) it creats 10K process and every process finds for callbacks of a hook for 3 keys (In mongooseim key means virtualhost).  
What benchmark scenario are you looking for? I can add new scenarios to its benchmark. I did not test **one** lookup, because in our Ejabberd based production with 2 million online users (about 400,000 per node) I'am sure that there is not just one lookup at the same time.

**Comment by Pouriya-Jahanbakhsh** [comment]
Today I will run benchmark on a good system not my laptop :+1:.

**Comment by arcusfelis** [comment]
So, code compilation is a cool idea we always wanted to tried.
And we actually do some dynamic module compilation for our backend modules :)

Why are we not using it yet?
Here are some considerations.

1. There are systems that use A LOT of virtual hosts. It's a pretty rare setup, usually majority of people is using just one domain. In this particular setup hosts can be added and removed without whole server restart. Sometimes mongooseim application start can be a performance issue, because we need to compile all these backend modules.

2. General thing about code:purge. code_server broadcasts a message to each process in the system and then waits for reply. With 2 mln processes it receives 2 mln messages into its mail box. Which is kinda not efficient (and also makes our monitoring systems hit a false alarm). Additional usage of dynamic modules can be done only after someone confirms that code server would not be an issue ;)

But we can use the library as one of backends for hooks storage, because it fits well for 90% of our setups (i.e. where we create hook bindings once and never change during server running). But I want to keep the ETS backend option too.

There are two ways to keep the ETS backend option:
- make a compile time flag
- make it configurable, and maybe keep this option inside a dynamically compiled module

It would be useful to have backend selection option to have in the library itself.

**Comment by Pouriya-Jahanbakhsh** [comment]
Hi @arcusfelis.

> There are systems that use A LOT of virtual hosts.  

In `posthaste` A LOT of vhs means A LOT of function clauses for a hook. I think Erlang does binary search for this (Not sure). Suppose you have a `user_send_packet` hook registered with 3 vhs, in `posthaste` you will have:  
```erlang
user_send_packet(VH1) ->
    [{Priority, {Mod, Func}}, ...];
user_send_packet(VH2) ->
    [{Priority, {Mod, Func}}, ...];
user_send_packet(VH3) ->
    [{Priority, {Mod, Func}}, ...];
user_send_packet(_) ->
    [].
```

> Sometimes mongooseim application start can be a performance issue, because we need to compile all these backend modules.  

Posthaste provides a feature for this. in start phase you can call `posthaste:keep(PostHasteProc)` and it will kepp all requests. After adding all hooks, call `posthaste:dump(PostHasteProc)` and it will compile all requests one time.  

> 2. General thing about code:purge. code_server broadcasts a message ...  

In posthaste each handler process will unload its hook module in terminate callback of gen_server. In MongooseIM i think it does this in stop phase. (Am i right?).

**Comment by kzemek** [comment]
@Pouriya-Jahanbakhsh Could you quickly compare `posthaste` to `goldrush`?

**Comment by fenek** [comment]
@Pouriya-Jahanbakhsh 

Please do open a PR, so it can be tested by our automated load testing environment.

**Comment by Pouriya-Jahanbakhsh** [comment]
@kzemek It sounds that **goldrush** has generic approach and can be used for hooking too (I think, i did not use). But i wrote **Posthaste** only for hooking.

**Comment by Pouriya-Jahanbakhsh** [comment]
@fenek 
Do you want to replace with ETS? or have an environment variable in compile time for this?

**Comment by fenek** [comment]
@Pouriya-Jahanbakhsh 

Just for executing automated load tests you may replace `ejabberd_hooks` with hardcoded Posthaste alternative in a PR. :)

**Comment by fenek** [comment]
We're not introducing any new runtime-compiled modules currently. The moment when we can use Persistent Terms is not that far in the future.
