### ISSUE TITLE
stream policy error while connecting to the server

### ISSUE THREAD

**Issue by sandy5487** [esl/MongooseIM#1881]
MongooseIM version: 2.1.1
Installed from: Ubuntu Package
Erlang/OTP version: the one that comes with 2.1.1

Sometimes while connecting to the server this error comes in log:

```
<stream:error>
<policy-violation xmlns="urn:ietf:params:xml:ns:xmpp-streams"/>
<text xmlns="urn:ietf:params:xml:ns:xmpp-streams" xml:lang="en">session in resume state cannot accept incoming stanzas</text>
</stream:error>
```

Regards
Sandeep

**Comment by vkatsuba** [comment]
Hi @sandy5487 

(C) The server either (1) is closing the existing stream for this entity because a new stream has been initiated that conflicts with the existing stream, or (2) is refusing a new stream for this entity because allowing the new stream would conflict with an existing stream (e.g., because the server allows only a certain number of connections from the same IP address or allows only one server-to-server stream for a given domain pair as a way of helping to ensure in-order processing

For more details please follow this link [streams-error-conditions](https://xmpp.org/rfcs/rfc6120.html#streams-error-conditions)
Hope this can help you.

Regards,
V. Katsuba

**Comment by ludwikbukowski** [comment]
@sandy5487 
other reason may be that the previous session was terminated (e.g you enabled `mod_ping` on server side but didn't on client side) and you try to send data over the same TCP stream. Basically, the process responsible for handling the connection in in the `resume` state [1] and it receives a stanza

[1] https://github.com/esl/MongooseIM/blob/master/src/ejabberd_c2s.erl#L1093

**Comment by sandy5487** [comment]
@ludwikbukowski 
Yes, I have enabled the `mod_ping` on the server side but what I have to do on the client side. 
Currently, on the client side, I am receiving the pings from the server and the same code is running well on the ejabberd server with the same configuration.

I am a little bit confused here, please suggest what to do.

Thanks

**Comment by ludwikbukowski** [comment]
@sandy5487 
I **suspect** that the flow might be as follow:
- user connects to mongooseim sucessfully and enables [stream management](https://xmpp.org/extensions/xep-0198.html) (stream resumption feature)
- user doesn't respond to mongooseim's pings
- mongooseim is configured so that it kills connection when user doesn't respond to pings
- user tries to send a stanza over existing connection but he receives the error because connection in in the "resume" state (waiting for stream resumption)

**Comment by fenek** [comment]
@sandy5487 

Is your issue still valid? If so, can  you please follow @ludwikbukowski instructions to debug it further?
