### ISSUE TITLE
Could not find element archive_wait in Config.

### ISSUE THREAD

**Issue by Beisenbek** [esl/MongooseIM#1971]
MongooseIM version: 3.0.0
Installed from: source
Erlang/OTP version: 18

Getting warning when running `big_test` for `rest_client_SUITE`

```
*** CT 2018-07-10 16:11:59.540 *** View log from node mongooseim@localhost when started mongooseim@localhost_915.html
Could not find element archive_wait in Config.
```
How I can pass it in config? Thanks.

**Comment by michalwski** [comment]
Hi @Beisenbek 

As far as I can tell this issue was related to your PR #1976 and #1938.
In tests you can pass the `archive_wait` option like below:
```erlang
[{archive_wait, timer:seconds(X)} | Config]
```

In one of the `init_per_*` functions (for instance `init_per_suite` or `init_per_group`).

I'm closing this issue since you finally used other way to wait for the message to be archived.
