### ISSUE TITLE
Use only one lib for JSON

### ISSUE THREAD

**Issue by michalwski** [esl/MongooseIM#1987]
Currently we use 3 different libs for encoding/decoding JSON:
* `mochijson2` (in the code)
* `jsx` (in big_tests)
* `jiffy` (in all places: code, small and big tests)

I personally think that using `jiffy` in all places is ok.

**Comment by fenek** [comment]
Do not forget about our dependencies. :) None of them use `mochijson2`, but:

`erlcloud`, `jwerl`, `nklib`, `tirerl` use `jsx` and only `nklib` uses `jiffy` by default but MAY use `jsx` as well. Switching to `jsx` will allow us to bundle only one dependency instead of 3. :)

However, JSON codec in C is definitely a strong advantage of `jiffy`, so I think I'd vote for it anyway.

**Comment by michalwski** [comment]
I moved that to JIRA: MIM-134
