### ISSUE TITLE
Get read message status for muclight room

### ISSUE THREAD

**Issue by Beisenbek** [esl/MongooseIM#2015]
MongooseIM version: 3.0.0
Installed from: source
Erlang/OTP version: 21

Is it possible to know from MIM that: 
1) exact message was delivered to (read by) all muclight_room participants
2) get the list of participants in muclight_room who already received (read) message

**Comment by fenek** [comment]
Hi @Beisenbek 

In order to be 100% sure that these messages have been received (and processed) by other participants, they need to reply with Chat Marker. It will be broadcasted in a room, thus delivered to the original sender.

Unfortunately MUC Light does not aggregate these markers automatically and does not store the list of confirmations per message. It means you'll have to be careful about possible marker broadcast storms.

**Comment by Beisenbek** [comment]
@fenek thanks.
