### ISSUE TITLE
MUC Light filter by roomname

### ISSUE THREAD

**Issue by mbrostami** [esl/MongooseIM#2197]
MongooseIM version: 3.2.0
Installed from: pkg
Erlang/OTP version: ?

I need to get MUC light rooms for a logged in user filtered by room name or room configurations.
Is it possible to do with MUC light or any alternative way?

**Comment by fenek** [comment]
Mi @mbrostami 

You may retrieve a full list of rooms with a disco request as specified in https://mongooseim.readthedocs.io/en/latest/open-extensions/muc_light/#33-discovering-occupied-rooms
Unfortunately it's not possible to perform any server side filtering. In case of configuration, you'd have to fetch the configuration of every occupied room and filter on client side. In case of room name it's a bit easier, because `name` attribute in disco response is set to a value of `roomname` room's config option.

**Comment by fenek** [comment]
@mbrostami You may paginate through the result set backwards with `before` RSM element. Please either use your XMPP client library API to do so, or manually construct an RSM subelement according to https://xmpp.org/extensions/xep-0059.html#backwards
