### ISSUE TITLE
XMPP Smack paging through Disco Items - MUC Light Rooms

### ISSUE THREAD

**Issue by sureshmopidevi** [esl/MongooseIM#2364]
MongooseIM version: 3.3.0-181-g7239b6a9c
Installed from: pkg
Erlang/OTP version: 21 [erts-10.3]

**Describe the issue.**
I am trying to use MongooseIM MUC Light module in my application. Everything works fine but I am not able to load more than 10 MUC Light chatrooms. As per the doc, it will return only the first 10 rooms and then we have to paginate them.

MUC Light: https://mongooseim.readthedocs.io/en/latest/open-extensions/muc_light/

Here is the response received, when MUC rooms request is sent.
```
<iq from='muclight.shakespeare.lit'
   id='hx51v49s'
   to='hag66@shakespeare.lit/pda'
   type='result'>
   <query xmlns='http://jabber.org/protocol/disco#items'>
       <item jid='alls-well-that-ends-well@muclight.shakespeare.lit'
             name='Everybody dies'
             version='1'/>
       <item jid='as-you-like-it@muclight.shakespeare.lit'
             name='As you like it'
             version='2'/>
       .
       .
       .
       <set xmlns='http://jabber.org/protocol/rsm'>
           <first index='0'>alls-well-that-ends-well@muclight.shakespeare.lit</first>
           <last>henry-the-fifth@muclight.shakespeare.lit</last>
           <count>37</count>
       </set>
   </query>
</iq>

```
Here you can notice the <set/> node with pagination information. Currently I am using below Smack code to get the chat rooms.
```
public DiscoverItems getMUCLightRooms() {
        DiscoverItems discoverItems = null;
        try {
            discoverItems = ServiceDiscoveryManager.getInstanceFor(mXMPPConnection).discoverItems(JidCreate.from(MUC_LIGHT_SERVICE_NAME));
        } catch (Exception e) {
            e.printStackTrace();
        }
        return discoverItems;
    } 
```
Here, the list of items contains DiscoverItems which contains information about the rooms. But I am not sure how to get the paging information from the response. I want to get the **first**, **last** and **count** values from the response.

I have inspected the DiscoverItems class, it doesn't have the paging information (RSMSet) include.

Can somebody help me on this?

**Comment by NelsonVides** [comment]
Hi @sureshmopidevi,

When you mention muclight loaded rooms, I understand that you want to query for the rooms a user occupies, right? As explained in the docs exactly here: https://mongooseim.readthedocs.io/en/latest/open-extensions/muc_light/#33-discovering-occupied-rooms

It seems to me that this is a question for Smack. They even have a specialised muclight manager, but no mention to paging or rms either in the [docs](https://github.com/igniterealtime/Smack/blob/master/documentation/extensions/muclight.md), not in the [source code](https://github.com/igniterealtime/Smack/blob/99232683915286e61d17a0e4c7fcf61f6529a31f/smack-experimental/src/main/java/org/jivesoftware/smackx/muclight/MultiUserChatLightManager.java#L129), where it actually just extracts the Jids of the given elements in the collection, it's not obvious to me either how to paginate.

Have you found out a solution for this problem? Can you let us know if the problem lies on the Smack side or if there's something unclear in MIM?

**Comment by sureshmopidevi** [comment]
I haven't found the answer yet. Seems XMPP is not suitable for my business use case. So I shifted to Firebase model chat solution
