### ISSUE TITLE
RDBS password is leaked in the logs.

### ISSUE THREAD

**Issue by Varmtech** [esl/MongooseIM#2596]
MongooseIM version: 3.5.0
Installed from: pkg
Erlang/OTP version: 22

When the log level is set info the and rdbs is configured then the rdbs credentials are leaked in the logs when the node starts.

2020-01-16 13:30:45.414 [notice] <0.98.0>@lager_file_backend:141 Changed loglevel of /var/log/mongooseim/ejabberd.log to info
2020-01-16 13:30:45.555 [info] <0.562.0>@mongoose_wpool_mgr:handle_call:93 event=starting_pool, pool=rdbms, host=global, tag=default, pool_opts=[{workers,10}], conn_opts=[{server,{pgsql,"xxxxxx.xxxxx.eu-central-1.rds.amazonaws.com",5432,"mongooseim","postgres","**Passformangooseim**"}}]

**Comment by gustawlippa** [comment]
Thanks for letting us know! We're working on the fix.

**Comment by DenysGonchar** [comment]
connection options are not disclosed in `info` logs any more. However, as secretes passed as usual function parameters there's no way to guaranty that they won't be disclosed in case of failures/crashes.

In the further releases we will try to figure out some MIM generic solution to avoid such disclosure on failures from our code base. But keep in mind that we still have to pass secretes as parameters to the 3rd party libraries (e.g. epgsql, mysql-otp, etc). and as it's in the nature of the erlang, most of them work asynchronously. so we have no means to catch/handle all the exceptions in that libraries, and for sure we don't want to disable standard lager logging of crashes.

Taking all this into account, our general recommendation would  be to avoid public sharing of MIM logs and restrict DB host access from the outside.

**Comment by erszcz** [comment]
@DenysGonchar 
[`epgsql` is secure](https://github.com/epgsql/epgsql/blob/devel/src/commands/epgsql_cmd_connect.erl#L100-L117) with regard to storing the password or printing it due to a crash, since it hides it in a fun. Could we apply the same technique in our code, check if other DB drivers do the same, and possibly PR patches if they do not?
Once we have that, I wouldn't remove logging connection options completely - the password wouldn't be visible anymore anyway, while the rest is useful for troubleshooting.
cc @michalwski

**Comment by michalwski** [comment]
Thanks for the update @erszcz. This sounds like a good approach to take wrt passwords in logs.
