### ISSUE TITLE
mod_http_upload_s3 error upload

### ISSUE THREAD

**Issue by krot3232** [esl/MongooseIM#2777]
MongooseIM version: 3.7
Installed from: source
Erlang/OTP version: Erlang/OTP 22 [erts-10.5.2]
cfg: add option mod_http_upload {add_acl,true} 

S3 file send PUT `http://zz:8000/dev/jabber/39e517297e4ff936e875536f4095d5968da54d944bf924ecc6f762850a32657b/index.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=accessKey1%2F20200618%2Feu-west-1%2Fs3%2Faws4_request&X-Amz-Date=20200618T124350Z&X-Amz-Expires=120&X-Amz-Signature=38fddb1e7fb1dc21ce4dc1ea84d32ffa46f89b49ae362bcded4dbde0b3150c57&X-Amz-SignedHeaders=content-length%3Bcontent-type%3Bhost%3Bx-amz-acl`
Error 403 Forbidden
`<?xml version="1.0" encoding="UTF-8"?><Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided.</Message><Resource></Resource><RequestId>629dd23fe2408696bd10</RequestId></Error>`
the file is uploaded to s3 if modify the code mod_http_upload_s3:create_queries
`create_queries(UTCDateTime, AccessKeyId, Region, ExpirationTime, ExpectedHeaders) ->
    Scope = aws_signature_v4:compose_scope(UTCDateTime, Region, <<"s3">>),
    SignedHeadersSemi = << <<H/binary, ";">> || H <- maps:keys(ExpectedHeaders) >>,
    SignedHeaders = binary_part(SignedHeadersSemi, 0, byte_size(SignedHeadersSemi) - 1),
    #{
       <<"X-Amz-Algorithm">> => <<"AWS4-HMAC-SHA256">>,
       <<"X-Amz-Credential">> => <<AccessKeyId/binary, "/", Scope/binary>>,
       <<"X-Amz-Date">> => aws_signature_v4:datetime_iso8601(UTCDateTime),
       <<"X-Amz-Expires">> => integer_to_binary(ExpirationTime),
       <<"X-Amz-SignedHeaders">> => SignedHeaders,
    <<"x-amz-acl">> =>  <<"public-read">>
     }.`

**Comment by DenysGonchar** [comment]
`The request signature we calculated does not match the signature you provided.` - looks like you're missing `x-amz-acl` header in your PUT request (on the client side).

The proposed modification just reverts the changes in this [commit](https://github.com/esl/MongooseIM/commit/adde7ed8a628a741e0efa268243ddf2cb857caa9#diff-935ab56c0a8c4be39c6d490466b0f4aeL66). The previous version of the code works only because Amazon ignores their own [spec](https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-query-string-auth.html): 

- __Canonical Headers must include the HTTP host header. If you plan to include any of the x-amz-* headers, these headers must also be added for signature calculation. You can optionally add all other headers that you plan to include in your request. For added security, you should sign as many headers as possible.__

For more information please see the [documentation](https://mongooseim.readthedocs.io/en/latest/modules/mod_http_upload/#testing-s3-configuration), also you may want to check this [PR](https://github.com/esl/MongooseIM/pull/2708) and this [discussion](https://github.com/minio/minio/issues/5083).
