### ISSUE TITLE
why mam for muclight should not include prev-version?

### ISSUE THREAD

**Issue by zhiphe** [esl/MongooseIM#2822]
MongooseIM version: 3.7.1
Installed from: source
Erlang/OTP version: 22

Describe the issue.
Can someone explain why MAM for muclight must not include prev-version?
<img width="693" alt="image" src="https://user-images.githubusercontent.com/3303588/90477980-eeee6e00-e15e-11ea-8652-28c1fec467b2.png">

**Comment by fenek** [comment]
Hi @zhiphe !

`prev-version` element is not stored in the archive, because we assume a client can retrieve consistent and complete set of messages from MAM, so there is no need for additional checks for previous version. This element was meant to be an additional helper for a client application to detect it might have inconsistent local state (i.e. mismatched local version and received prev-version).
