### ISSUE TITLE
Offline muc light message in mod _offline table

### ISSUE THREAD

**Issue by pworldx** [esl/MongooseIM#3090]
MongooseIM version: 4.0.1
Installed from: source

Describe the issue.

I want to store muc light message in mod offline table. Is there any configuration I have to do it in toml file to store the muc light messages.

**Comment by DenysGonchar** [comment]
[store_groupchat_messages](https://esl.github.io/MongooseDocs/latest/modules/mod_offline/#modulesmod_offlinestore_groupchat_messages) is the option you are looking for. it should be supported at 4.0.1, just not documented.

however, we highly recommend to use MAM MUC storage instead of mod_offline for MUC/MUC-light. you can find more details here - https://github.com/esl/MongooseIM/pull/2992

**Comment by chrizkiran** [comment]
@DenysGonchar when i had store_groupchat_messages to .toml config file, it says unexpected key, may i know what am I doing wrong

**Comment by protostartup** [comment]
@DenysGonchar I have added "store_groupchat_messages" to my .toml config file, but I get unexpected key error, can you enlighten me on how the config should look to enable offline messages for muc-light group chats
