### ISSUE TITLE
Implement user removal from MUC light in REST administrative APIs

### ISSUE THREAD

**Issue by apontini** [esl/MongooseIM#3388]
MongooseIM version: 5.0.0
Installed from: /
Erlang/OTP version: /

Hello everyone!
While reading the [MongooseIM's REST API for backend administration](https://esl.github.io/MongooseDocs/latest/rest-api/Administration-backend/) documentation, I found out that there's no API to kick a user from a MUC light but only one to delete the room.

My question is: is this something that's not possible (maybe I'm missing something about MUC light implementation) or can it be implemented?
IMHO it would be useful for backend related operations to expose such API without the need to authenticate the user that's performing the action, as it's required with the client/frontend APIs.

**Comment by chrzaszcz** [comment]
We are developing new [GrapQL API](https://github.com/esl/MongooseIM/tree/feature/graphql) now. This issue will not be present in the new API anymore. Do you still need this feature in the REST API?

**Comment by apontini** [comment]
It would be nice to have, yes. Right now our workflow (including code generators, libraries etc.) assumes REST as a convention between our services.

**Comment by gustawlippa** [comment]
Hi @apontini!
I'll create a ticket in the backlog for this, but being honest, our open source team is rather small at the moment, and focused on introducing the GraphQL API. Our plan is to develop and improve it instead of the REST API, so I'm afraid it can be long before this feature is introduced if ever.
If you really need this feature, you could consider sponsoring it. It doesn't seem too big to implement, and maybe we could shift our priorities and deliver it as well. Please reach out to us at https://www.erlang-solutions.com/contact/ if you would be interested.

**Comment by apontini** [comment]
Got it! I just have a couple questions then:

- Will the GraphQL API include this feature?
- Is there any ETA for this new APIs?

**Comment by gustawlippa** [comment]
* Yes, it'll be included in the GraphQL admin API (user's API as well, similarly to current REST API)
* We're aiming at the end of Q2 2022 to introduce the GraphQL API.

**Comment by chrzaszcz** [comment]
I am closing this one, because we have moved to GraphQL, and the REST API is no longer being extended.
