### ISSUE TITLE
Compile MongooseIM 1.5.0 failed

### ISSUE THREAD

**Issue by raymond852** [esl/MongooseIM#351]
I cloned the stable branch and tried to compile it. When I tried 'make rel', I got this error:

==> rel (generate)
ERROR: generate failed while processing /Users/hy110831/git/MongooseIM/rel: {'EXIT',{{badmatch,{error,"odbc: Missing application directory."}},
         [{rebar_reltool,generate,2,[]},
          {rebar_core,run_modules,4,[]},
          {rebar_core,execute,5,[]},
          {rebar_core,process_dir1,6,[]},
          {rebar_core,process_each,5,[]},
          {rebar_core,process_dir1,6,[]},
          {rebar_core,process_commands,2,[]},
          {rebar,main,1,[]}]}}

I also download the source code from the website, still getting the same error, any help would be appreciated

**Comment by ppikula** [comment]
It's because you don't have odbc libraries installed in your system, what operating system do you have ? 
If you don't need odbc backend you can run `make configure with-mysql with-pgsql` and you will get support for mysql and postgres. To get the full list of available options use `make configure` without params.

**Comment by raymond852** [comment]
Thanks for ur quick reply. I just realized my Erlang installation did not include the ODBC module. Fixed it by reinstalling Erlang, and by the way, I am using the stable branch instead of the master branch, so there is no ‘make configure’ on the stable branch. Thanks for your help again.
