### ISSUE TITLE
Using elasticsearch & cassandra

### ISSUE THREAD

**Issue by harshagarwal00** [esl/MongooseIM#3681]
MongooseIM version: (put the version)
Installed from: (source or pkg)
Erlang/OTP version: (put the version)

Is there a way to use both cassandra as well as elasticsearch to store messages.
Use case: need full text search capability of elasticsearch and reliability of cassandra

**Comment by chrzaszcz** [comment]
It is possible to configure one backend for one-to-one messages and a different one for groupchat messages:

```toml
[modules.mod_mam]
  pm.backend = "cassandra"
  muc.backend = "elasticsearch"
```

However, it is not possible to enable more than one backend for one domain for `pm` (and the same is true for `muc`). This is currently not on our roadmap, because it is non-trivial. We will put it on our roadmap if there is more demand or if you are interested in sponsoring the effort.

**Comment by pawlooss1** [comment]
Closing the issue due to lack of activity.
