### ISSUE TITLE
MongooseIM 5.1.0 rpm for Centos8

### ISSUE THREAD

**Issue by ppcharli** [esl/MongooseIM#3717]
MongooseIM 5.1.0 rpm for Centos8 is not available for download at https://www.erlang-solutions.com/downloads/
Is it planned to release it?

Thanks

**Comment by chrzaszcz** [comment]
Thanks for pointing this out. This is a mistake on our side and we will add the package soon. In the meantime you could try to use the one for Centos 7, as it can be installed and MongooseIM starts up correctly.

**Comment by arcusfelis** [comment]
CentOS 8 is End of Life, so our build deps are not updated and the build process crashes.
CentOS 7 is still supported till June 30, 2024 and received the required deps.
https://cloud.google.com/compute/docs/eol/centos-eol-guidance

Recommendation is to use Ubuntu, because there are probably **no security patches** for Centos8 anymore. And even if we fix the package, it is still not a recommended operating system to run.

**Comment by ppcharli** [comment]
And rpms for Rockylinux 8.0  AlmaLinux 8.0 
Is it planned to release it?

**Comment by ppcharli** [comment]
Is it planned to release MongooseIM 6.0.0 for Rockylinux 8.0 or AlmaLinux 8.0 ?

Thanks

**Comment by chrzaszcz** [comment]
> Is it planned to release MongooseIM 6.0.0 for Rockylinux 8.0 or AlmaLinux 8.0 ?
> 
> Thanks

We are not planning any other packages than Debian and Ubuntu at the moment. You can also use the [docker image](https://hub.docker.com/r/mongooseim/mongooseim/) or the [helm chart](https://artifacthub.io/packages/helm/mongoose/mongooseim).
