### ISSUE TITLE
Mongoose as XMPP server file transfering rate is low

### ISSUE THREAD

**Issue by OOOlledj** [esl/MongooseIM#3754]
MongooseIM version: 5.0.0.1
Installed from: pkg
Erlang/OTP version: 24

I deployed mongoose server on dedicated machine as XMPP server, and use Pidgin as client
The problem is file transfer - it is VERY slow, around 1 KiB/s. And file transferring starts not immidiately, but with 2-3 minutes delay.

I think it's something about server configuration, but don't know where to dig
/etc/mongooseim/mongooseim.toml configuration file seemed be not responsible for traffic as i thought with Shapre section

![slow](https://user-images.githubusercontent.com/52776316/188825667-02364791-415d-4e3c-ac31-abbcb76c3ef6.png)

Can you suggest, where the problem is?

**Comment by arcusfelis** [comment]
There are three ways to pass files in XMPP:
- one is to use XMPP stanzas to pass the parts of the file https://xmpp.org/extensions/xep-0096.html . Pretty bad performance, because of extra encoding into XML. Should not be used for big production installations.
- another is an external channel. the client use XMPP to negotiate an external channel (for example, WebRTC).
- third is mod_http_upload, the client asks the server to get an URL where the can upload the file using HTTP (usually into Amazon S3). Needs to be configured separately.

Disabling shapers in c2s listener config could help you because it seams that Pidgin tries to use the first method.

**Comment by OOOlledj** [comment]
So, bad file transferring performance is the XMPP feature and it's nothing to be done with it except separate channel?

**Comment by arcusfelis** [comment]
Bad transferring performance is the result of XML usage as a transport, so base16 encoding is needed.
And also servers are not optimised to handle gigantic messages.

Separate channel is not that of a problem as it sounds, audio and video calls also need some kind of webrtc integration.

**Comment by OOOlledj** [comment]
Than you for explanations.
I found more interesting for my purposes project - Rocket Chat.
