### ISSUE TITLE
Error responses do not contain access control headers set

### ISSUE THREAD

**Issue by prabhu** [esl/MongooseIM#385]
I am using mod_bosh which is setting access control headers correctly for success (200) responses. But for errors such as 504, 503 etc these headers are not set. I am temporarily using a proxy but would prefer a pure mongoose solution if possible.

Is there a possible workaround for this issue?

**Comment by michalwski** [comment]
Could you give us an example (curl command would be best) from which you expect an erroneous status?

**Comment by prabhu** [comment]
I tried my best but not able to reproduce the error with curl command. Below is one scenario,

1. My javascript based client is using AJAX long polling to keep the connection alive
2. After some time (Around 30 sec based on DEFAULT_INACTIVITY in mod_bosh.erl) connection times out and the server responds with 504.
3. This response however doesn't contain any access control headers and hence the browser is not letting the client know about this

Hope this helps.

**Comment by teseo** [comment]
I there any update on this? It also happens to me randomly

**Comment by michalwski** [comment]
Thanks for getting back to this issue. There was no work related to this recently as we were busy with other tasks. I'm re-opening this issue and try to fit it in 1.6.1 Milestone.

**Comment by astachurski** [comment]
According to section related to error handling in specification for XEP-0124 (http://www.xmpp.org/extensions/xep-0124.html, section 17.1 and 17.2) and the HTTP1.1 itself  (RFC7230) it can be concluded that upon BOSH session (and TCP connection subsequently) termination 
server does not need to provide any information in HTTP header as the termination reason is handled by lower level protocol - BOSH itself. In the xep there is explained how "legacy" and "new" clients should handle errors (including normal and abnormal session terminations due to, for example, inactivity timeouts). So I think the way MongooseIM behaves right now is correct in this respect. When I think about possible walkarounds for "missing" ACAO headers (when, for example javascript client tries to fall back to some cross-origin resource in such a case) - is to actually cache the ACAO data upon reception of status 200 and use it later if needed in case of timedout/broken connection. It is just not possible that these data would change over time of HTTP/Bosh session (beween first connection and session/connection broken to be exact). So, please consider the approach from XEP itself or cache the later needed headers on client side. 
brgds!

**Comment by astachurski** [comment]
@prabhu @teseo - please confirm you are okay with the explanation so that we can close the pr, cheers!

**Comment by teseo** [comment]
Seems ok to me.

**Comment by prabhu** [comment]
I am fine with the explanation too.
