### ISSUE TITLE
XEP-0440: SASL Channel-Binding Type Capability support

### ISSUE THREAD

**Issue by Neustradamus** [esl/MongooseIM#3921]
Dear @esl team,

Can you add "XEP-0440: SASL Channel-Binding Type Capability" support?
- https://xmpp.org/extensions/xep-0440.html

Thanks in advance.

**Comment by chrzaszcz** [comment]
Thanks for raising this issue. Currently we are only supporting the `tls-unique` channel binding type, so from my point of view the only benefit would be letting the client know about the support binding type, right? However, with #3721 we would need `tls-exporter` as well, so it might make more sense to explicitly tell the client what we support, even if there is a one-to-one mapping between binding types and TLS versions.

If there is any use case that you need the feature for, please let us know. It would help us understand the demand and thus prioritize it higher. Of course we are open for community contributions and feature sponsorship as well.

**Comment by pawlooss1** [comment]
Closing this issue for now due to lack of activity. We've created an internal backlog entry for this feature. Currently it is not on our roadmap but if the community demand increases we'll have a closer look at this. @Neustradamus if you would like to provide some additional info about use cases then feel free to reopen this issue or raise another one.
