### ISSUE TITLE
Too much postgres connection creating

### ISSUE THREAD

**Issue by vooolll** [esl/MongooseIM#394]
when I write ps aux I have 20+ processes (of  connection) to postgres how to fix it, I try to modify it with odbc_pool_size , but I still have this amount of connections. I am using mod_mam

**Comment by lavrin** [comment]
What is your `mod_mam` configuration in `ejabberd.cfg`? Depending on that `mod_mam` might use dedicated connections, whose creation does not abide the `odbc_pool_size` limit.

**Comment by JockeTF** [comment]
I'm having the same issue.

Because of this issue I had to change the maximum number of connections that my PosgreSQL server allows to 256. I'm also avoiding Micro instances on Amazon RDS for MongooseIM since it may result in the database server running out RAM.

Here are my settings related to ODBC and MAM:
https://gist.github.com/JockeTF/ab600b99142e8c789708

Here's how things look on our development server:
http://i.imgur.com/ZMEvCew.png

I'm not entirely against that if it is necessary for good performance. However, if it can be avoided in a good manner then it probably should be.

**Comment by lavrin** [comment]
Whoa, there are quite a few of them. I guess you, @JockeTF, host several XMPP domains on this server, don't you? If so, that's the reason - a new **ODBC connection pool is created per virtual host**.
There's a proprietary customization we've done to enable all virtual hosts to use the same ODBC pool, but open sourcing it is probably out of the question (the customer pays, the customer decides, sometimes that's just the way it is).

**Comment by JockeTF** [comment]
No, it's actually only one virtual host.

**Comment by lavrin** [comment]
Ok, I've found the reason. [`mod_mam_odbc_async_pool_writer` uses a hardcoded pool size of 32][1]. This pool is a separate one from the general one whose size is limited by `odbc_pool_size`.

[1]: https://github.com/esl/MongooseIM/blob/899cd2360af3bca62c99764688ea6cac99b14d59/apps/ejabberd/src/mod_mam_odbc_async_pool_writer.erl#L60-L61

**Comment by lavrin** [comment]
So in order to minimize the number of dedicated connections for `mod_mam` you can use `mod_mam_odbc_async_writer` instead.

**Comment by JockeTF** [comment]
Great, thank you! I'll make sure to do that for out development server.

Any chance of getting a configuration option for the pool size though?

**Comment by lavrin** [comment]
We'll see what the future brings ;)

**Comment by JockeTF** [comment]
Thanks again!

Changing to mod_mam_odbc_async_writer does indeed remove 31 of the additional processes. There's still 35 of them left though, even with an odbc_pool_size of 2.

Perhaps there's something else there too? Or is this expected behavior?

**Comment by JockeTF** [comment]
Ah, nevermind. It was the MAM MUC async writer.
