### ISSUE TITLE
New swagger doc implementation for admin API

### ISSUE THREAD

**Issue by bartekgorny** [esl/MongooseIM#3987]
It is so nice to have client API done in the new way - it looks better and the "try it" feature works. Would be even nicer to have admin API done the same way.

**Comment by chrzaszcz** [comment]
Thanks for logging the issue. It is correct  that the Client REST API does indeed have the interactive Swagger UI, hosted at `https://localhost:8089/api-docs` by default, while the Admin REST API does not have it. The missing functionality is **not** on our roadmap, because we are moving away from REST in favor of [GraphQL](https://esl.github.io/MongooseDocs/latest/graphql-api/Admin-GraphQL/). The REST API is deprecated and will be removed in the future.

There are following alternatives:
- Using the [GraphQL reference](https://esl.github.io/MongooseDocs/latest/graphql-api/admin-graphql-doc.html)
- Using the GraphiQL Web UI, which for the Admin endpoint is hosted at `http://localhost:5551/api/graphql` by default.
- If you need to stick to REST, use the [Swagger Online `Docs](https://esl.github.io/MongooseDocs/latest/swagger/index.html), which shows the `curl` requests to copy+paste to your shell.
