### ISSUE TITLE
Inbox does not update unread counter correctly when not marking all messages as read

### ISSUE THREAD

**Issue by ZXDMNicola** [esl/MongooseIM#4036]
### **Issue Description:**

Currently, the inbox service in MongooseIM lacks the ability to set only specific messages as read, resulting in an inaccurate unread counter. The counter is reset only when all messages are marked as read, failing to reflect the actual number of unread messages when only a portion of the messages are marked as read using chat markers.

### **Steps to Reproduce:**

- Send from another user 20 messages inside a conversation.
- Use chat markers to mark only 10 out of the 20 messages as read.
- Check the unread counter for the inbox.

### **Expected Behavior:**

After marking 10 messages as read using chat markers, the unread counter should accurately reflect the remaining 10 unread messages.

### **Actual Behavior:**

When marking only some messages as read using chat markers, the unread counter remains unchanged at 20, even though the effective number of unread messages is 10.

**Comment by DenysGonchar** [comment]
I don't think we are going to implement this behaviour. While it's technically possible to implement, the implementation would be supper inefficient:

- the key problem is that chat marker message provides only message id to the server, not the number of message. 
- Inbox module tracks only the last message in the conversation (so it knows its id), and it can easily reset the counter in this case. 
- Otherwise, it requires making complex queries to MAM tables to understand the actual counter shift that corresponds to the random message id. 

From another side, the client application knows the exact adjustment for the unread counter. So client app can easily tell it to the server via IQ.

**Comment by ZXDMNicola** [comment]
Hi @DenysGonchar, thanks for the explanation!
