### ISSUE TITLE
MongooseIM responds with error service-unavailable to messages when mod_mam is active

### ISSUE THREAD

**Issue by artefactop** [esl/MongooseIM#413]
I have disabled mod_offline and mod_mam active to archive conversations, I don't understand why If Mongoose can save the message it return an error to sender:

```xml
<message xmlns='jabber:client' id='4' xml:lang='en' type='error' to='pepe@localhost/25201586071427471342294583' from='juliet@localhost'>
    <body>hello</body>
    <request xmlns='urn:xmpp:receipts'/>
    <archived id='A4I7NP5O1JG1' by='juliet@localhost'/>
    <error type='cancel' code='503'>
      <service-unavailable xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/>
    </error>
  </message>
```

Are there any way to avoid this behaviour without activating mod_offline?

**Comment by michalwski** [comment]
Sorry for such a late response.

The issue is caused by the offline hook used by mod_offline. When there is no callbacks for this hook `service-unavailable` is generated automatically. There is simple solution for that, you just need to use [this stub module] (https://github.com/esl/MongooseIM/blob/mod-offline-stub/apps/ejabberd/src/mod_offline_stub.erl)

**Comment by artefactop** [comment]
Thanks for your response
