### ISSUE TITLE
mongooseimctl debug

### ISSUE THREAD

**Issue by andrewvmail** [esl/MongooseIM#431]
Is mongooseimctl debug supposed to attach an interactive shell and give out verbose outputs on what the server is doing identical to running mongooseimctl live?

For some reason I can only go to mongooseimctl live to get verbose debug output of the server. Would be nice if I dont have to restart the server when ever I need to debug. Or maybe im missing something maybe.

Thanks in advance!

**Comment by lavrin** [comment]
You don't have to restart the server. Just go into the release directory from where the server is running and do `tail -f log/*`.

**Comment by lavrin** [comment]
For a longer answer: due to the architecture of console input/output in the Erlang VM, `mongoseimctl debug` doesn't output exactly the same things `mongooseimctl live` does. This stems from the fact that `live` runs the node in an interactive node, while `debug` runs a separate Erlang node and attaches a remote shell to the first actual server running in the background.

Logs which would hit the console in `live` mode also go the `log/console.log`, even when the server is running in the background.

**Comment by andrewvmail** [comment]
Thanks for the explanation!  Will tail the the log
