### ISSUE TITLE
"MongooseIM is not running in that node" error on 1.5.1

### ISSUE THREAD

**Issue by Suvitruf** [esl/MongooseIM#454]
I'm using MongooseIM 1.5.0 in one cluster. But now tried to install last version (1.5.1) to another server from repo and have error  when checking status:

    root@chat1:~# mongooseimctl status
    The node chat1@localhost is started with status: started
    MongooseIM is not running in that node
    Check for error messages: log/ejabberd.log
    or other files in that directory.

from here, i think, https://github.com/esl/MongooseIM/blob/8d387dd1e99b74ae409ce01e2f71b5a1281339c8/apps/ejabberd/src/ejabberd_ctl.erl#L152

So, i tried to attach mongooseim `/mongooseim attach` and tried `application:which_applications().`
and see 

    {mongoose,[],[]},
    {mnesia,"MNESIA  CXC 138 12","4.12.5"},
in list.

Same command on 1.5.0 instillation showing me list with:

    {mongooseim,mongooseim,"1.5.0"},
    {mnesia,"MNESIA  CXC 138 12","4.12"},

After I remove 1.5.1 from server and install 1.5.0 it works fine. 

I don't know is it bug in 1.5.1 or something else...

**Comment by lavrin** [comment]
Since the change is now merged in, you'll probably want to use the new version. I don't know when new prebuilt packages will be available, but maybe if you let us know which platform you need it might be the priority.
Sorry for vagueness and "maybes", but I don't know the procedures according to which packaging is carried out.

**Comment by Suvitruf** [comment]
Hello, Radosław.

I use Ubuntu commonly. For now in our Soft Layer servers we are using Ubuntu14.04-64 Minimal for VSI.
