### ISSUE TITLE
MongooseIM crash and die using mod_mam

### ISSUE THREAD

**Issue by artefactop** [esl/MongooseIM#496]
When I have a some load at DB (MySQL) MIM is not be able to control that situation and after some error like this one:
```
/srv/mongooseim/log/ejabberd.log.4:2015-08-31 15:28:08.236 [error] <0.260.0> Supervisor ejabberd_sup had child 'ejabberd_mod_mam_writer_localhost_6' started with mod_mam_odbc_async_pool_writer:start_link('ejabberd_mod_mam_writer_localhost_6', 6, <<"localhost">>) at <0.541.0> exit with reason timeout in context child_terminated
```
MongooseIM *die*. I Configured mod_mam on this way:
```
  %%
  %% Message Archive Management (MAM) for registered users.
  %%

  %% Only archives for c2c messages, good performance.
  {mod_mam_odbc_user, [pm]},
  {mod_mam_cache_user, [pm]},
  {mod_mam_mnesia_dirty_prefs, [pm]},
  {mod_mam_odbc_arch, [pm, no_writer]},
  {mod_mam_odbc_async_pool_writer, [pm]},
  {mod_mam, []}
```

What I'm doing wrong?

**Comment by michalwski** [comment]
Your configuration looks correct. The reason why MongooseIM dies is that the supervision tree for mam async writers was not configured correctly. This was fixed in master branch already but there is no new version yet.
On the other hand, such situation happens mainly when the DB is overloaded and not responding in reasonable time.
