### ISSUE TITLE
Want to create persistent MUC despite of all occupants offline and auto rejoin when they online

### ISSUE THREAD

**Issue by aadimurthy** [esl/MongooseIM#591]
Hi Team 
 
I wish to create new MUC room with some occupants and able to do the same with IM. But problem arise when any occupant goes offline which makes removal of occupant form room permanently . and one has to join again in the room when he comes online 

I want MUC room to be persistent with the all the members/occupants even though some of them are  offline  and would like to  deliver the offline messages  to those offline members when they come online 
i know this is little something different from standard XEP-045 but i want to make MongooseIM to support this with minimal changes .Is this possible with MongooseIM ?

**Comment by michalwski** [comment]
Yes, it's possible with MongooseIM. We have our own "MUC-light" which should satisfy your needs. Take a look a this PR #577 and let us know what do you think about it.

**Comment by aadimurthy** [comment]
Great ! This is what i exactly looking for !!  how can i add this support for my already installed MongooseIM ? seems there is implementation still going on . Could you please ping me the latest updated check-in branch if you know any. 
Thanks !

**Comment by fenek** [comment]
Hi aadimurthy,

The implementation is finished for the first release of this feature. If your MongooseIM installation uses latest (or reasonably recent) master branch, then you just need to merge `muc_light` branch into it. When it's done, please follow instructions in https://github.com/esl/MongooseIM/blob/muc_light/doc/modules/mod_muc_light.md to enable the extension.

Unfortunately it's not possible to just copy `mod_muc_light*.erl` modules, because this pull request involves modifications in other modules too.

**Comment by aadimurthy** [comment]
Thanks a million guys !! i will try this soon
