### ISSUE TITLE
in file ejabberd_listener.erl:175  , when call listen_tcp sucess  , it should add ets:delete(listen_sockets, { PortIPProto, ListenSocket}),

### ISSUE THREAD

**Issue by ChelinTsien** [esl/MongooseIM#711]
MongooseIM version: (put the version)
Installed from: (source or pkg)
Erlang/OTP version: (put the version)

Describe the issue.
in file ejabberd_listener.erl:171  , when call listen_tcp sucess , it should add ets:insert(listen_sockets, { PortIPProto, ListenSocket}),

**Comment by michalwski** [comment]
Thanks a lot for reporting this. This is very important issue. How did you find this?

**Comment by ChelinTsien** [comment]
IN file ejabberd_config:601, line 601&602 are the same with line 605&606, so i think you can delete one of them

**Comment by ChelinTsien** [comment]
@michalwski IN file ejabberd_config:601, line 601&602 are the same with line 605&606, so i think you can delete one of them

**Comment by bartekgorny** [comment]
I'm not sure it really should - the implementation dates back to 2010, and its purpose is to prevent mongoose crash on startup if a port is in use. It supports only xml_stream ports, and it works, though (a) there is no test to prove it, and (b) I'm not sure this is a desired behaviour. If an xml ports (e.g. c2s) is in use then mongoose starts fine and doesn't event issue warnings, it just doesn't receive any data because everything is captured by the other application using this port. One might argue that if an app can not use a port it needs then it should crash (as it indeed does if you block a port used by cowboy).

**Comment by bartekgorny** [comment]
Turns out that the real reason why ejabberd can be started when something listens on its port is this:
`{reuseaddr, true},`
in ejabberd_listener. It's been there since the very beginning (entered by Alexey Shchepin in 2002). It can be removed or changed to 'false', this makes the daemon properly crash on startup if a port is in use, but it makes it very difficult to restart listeners because if the process keeps running then broken connections still hang around for a while in a transitional state making in impossible to bind to the port again (if reuseaddr is false). It could probably be solved somehow, I'm not sure it is worth the effort.
