### ISSUE TITLE
It's not possible to remove dead node from cluster

### ISSUE THREAD

**Issue by studzien** [esl/MongooseIM#739]
MongooseIM version: (master, 2c322ab35d7)

After removing ``remove_from_cluster`` command from ``mongooseimctl`` it's not possible to remove a node that is already dead and is not coming back.

**Comment by michalwski** [comment]
In other words we need to restore `mongooseimctl remove_from_cluster` removed in #717.

**Comment by ludwikbukowski** [comment]
I can restore `add_to_cluster` and `remove_from_cluster` but rewriten in the `mongoose_cluster.erl` module so the lines in the `nodetool [1]` would be removed. 
Then there will be four commands available:
- `join_cluster`
- `leave_cluster`
- `add_to_cluster`
- `remove_from_cluster`

Maybe also change the names of the new commands to `join_node` (instead of `add_to_cluster`) and `leave_node` (instead of `remove_from_cluster`)? Then the command names would be more consistent. 
However it would break backward name compability...
What do you think?

[1] https://github.com/esl/MongooseIM/blob/8112a1db3792f96e891f69120f946bb5cabe72ee/rel/files/nodetool#L55

**Comment by michalwski** [comment]
The only relevant command from previous version is `remove_from_cluster` from the reason described in this issue. There is no need to restore other commands.
