### ISSUE TITLE
Any way to create and configure room in the command line

### ISSUE THREAD

**Issue by vsching** [esl/MongooseIM#845]
Hi there, i am using mongooseim as a mobile side backend, the problem is, sometimes network connection is weak, and the app create a chatroom, but failed to configured it.

Is there anyway i can customize this behavior, or any command i can create the room as an admin instead?

Something like ejabberdctl create room?

**Comment by ludwikbukowski** [comment]
At the moment we do not support admin commands for creating muc room (`mongooseimctl create_room`). I'm sure we will add it soon.
However you can still create rooms it in the mongooseim erlang console. Depending on the muc module you use:
- For our new [Muc light](https://xmpp.org/extensions/inbox/muc-light.html) implementation use `mod_muc_light_db_backend:create_room/4` e.g:
````
(mongooseim@localhost)3> mod_muc_light_db_backend:create_room({<<"RoomU">>,
<<"muclight.localhost">>}, [{roomname,<<"Untitled">>},{subject,<<>>}],
 [{<<"user@localhost">>, owner}], <<"ver-1">>).
{ok,{<<"RoomU">>,<<"muclight.localhost">>}}
````
- And for [legacy version](http://xmpp.org/extensions/xep-0045.html) mod_muc:
````
(mongooseim@localhost)3> mod_muc:create_instant_room(<<"localhost">>,
<<"roomname">>, {jid, <<"user">>, <<"localhost">>, <<"resource">>, <<"user">>, 
<<"localhost">>, <<"resource">>}, <<"nick">>, []).
ok
````

**Comment by vsching** [comment]
thanks, will test it out, btw, does the room still need to be unlocked? And can you provide me how to unlock room with default configuration profile using the erl console?

Sorry for the inconvenience.
I am still trying to understand the source code, not too familiar with erlang.

**Comment by ludwikbukowski** [comment]
I guess you're using [XEP-0045](http://xmpp.org/extensions/xep-0045.html) as it's standard multi user chat extension and you have `mod_muc` enabled in your `ejabberd.cfg` file
As I wrote above, creating a new room is done by calling `mod_muc:create_instant_room/5`
The configuration list is passed as a last argument of the function call. It's the list of key-valued tuples 
e.g:
>
(mongooseim@localhost)3> mod_muc:create_instant_room(<<"localhost">>,
<<"roomname">>, {jid, <<"user">>, <<"localhost">>, <<"resource">>, <<"user">>, 
<<"localhost">>, <<"resource">>}, <<"nick">>**,[{title, <<"Simple room">>}{persistent, true}, {max_users, 10}]**).
ok
>

will create new room named "_Simple room_" with maximum user count set to 10 and room will be persistent.
The whole list of options with description you can find in docs:
http://mongooseim.readthedocs.io/en/latest/modules/mod_muc/ in `default_room_options` section.
 It's also filled with default values

Going back to your question; after room creation you don't need to unlock the room, because the default options are set so that everyone can join the room
