### ISSUE TITLE
Cannot retrieve muc light history

### ISSUE THREAD

**Issue by ludwikbukowski** [esl/MongooseIM#867]
MongooseIM version: e9e51c07b8d33b1b845555e9fc6a2d9bd3c72560 (staging server)
Installed from: source
Erlang/OTP version: 17.5

Due to [Muc light documentation 6.2.1 Groupchat message from occupant](https://xmpp.org/extensions/inbox/muc-light.html#mam) I send:
``` xml
<iq type='set' id='mamget1' to='9f8870da-8c7c-4c95-90d8-cb9da5797b3a@muclight.erlang-solutions.com'>
    <query xmlns='urn:xmpp:mam:1' queryid='f27' />
</iq>
```

and got `not-implemented` response:

``` xml
<iq from="9f8870da-8c7c-4c95-90d8-cb9da5797b3a@muclight.erlang-solutions.com" type="error" xml:lang="en" to="gardano@erlang-solutions.com/Administrators-MacBook-Pro" id="mamget1">
<error type="cancel" code="501">
<feature-not-implemented xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/>
</error>
</iq>
```
but when I send usual mam request:
``` xml
<iq type="set" id="AAED246C-1E85-451B-AA17-ACEF6A8AF34B">
<query xmlns="urn:xmpp:mam:1" queryid="A098413D-45BB-4E13-AEFC-98500A21E396">
<x xmlns="jabber:x:data" type="submit">
<field var="FORM_TYPE" type="hidden"><value>urn:xmpp:mam:1</value>
</field>
<field var="with">
<value>9f8870da-8c7c-4c95-90d8-cb9da5797b3a@muclight.erlang-solutions.com</value>
</field>
</x>
<set xmlns="http://jabber.org/protocol/rsm">
<max>5</max>
<after></after>
</set>
</query>
</iq>
```
I got `result` response:
``` xml
<iq from="gardano@erlang-solutions.com" type="result" to="gardano@erlang-solutions.com/Administrators-MacBook-Pro" id="AAED246C-1E85-451B-AA17-ACEF6A8AF34B">
<fin xmlns="urn:xmpp:mam:1">
<set xmlns="http://jabber.org/protocol/rsm">
<first index="0">ADEADD3DPEG1</first>
<last>ADEG9NJFDN01</last>
<count>10</count>
</set>
</fin>
</iq>
```
And I got the messages. 
Could it be related to the configuraion? 
`muc_light` config:
```
 {mod_muc_light, [{host, <<"muclight.erlang-solutions.com">>},
                   {rooms_in_rosters, false}, 
{rooms_per_page, infinity}, {max_occupants, infinity}, 
{all_can_invite, true}, {all_can_configure, true}]},
```

**Comment by ludwikbukowski** [comment]
It was about specifying `muclight` host in `mod_mam_muc` module:
```
{mod_mam_muc, [{host, "muclight.erlang-solutions.com"}]}
```

**Comment by vickydhas** [comment]
To add on this is what I have done to get the configuration setup and successfully establish MUC Light History.

My Configuration for better understanding 
1) MongooseIM server Beta 2.0.0
2) Erlang OTP : 18
3) IOS Robiehanson  framework, but i configure the IQ's manually instead of using XMPPMUCLight as Mongoose fromId if sent with resource like username@hostname/**IOS** gives error. Hence cannot use this default XMPPMUCLight CLass.


1. ejabberd.cfg file

```
    % Added MUC-Light support for the group chat
   {mod_muc_light, [{host, "muclight.@HOST@"}]},

   % Enabled MUC for the support to MUC-Light dependancy if any
   {mod_muc, [{host, "muc.@HOST@"}, {access, muc},{access_create, muc_create}]},

   %Enabled Mod Archive for the MUC chats as MUC-Light offline logic work on this
   {mod_mam_muc, [{host, "muc.@HOST@"}]},

   %Enabled this configuration for the MUC Archive message support
   {mod_mam_odbc_user, [muc]},
   {mod_mam_cache_user, [muc]},
   {mod_mam_muc_odbc_arch, [no_writer]},
   {mod_mam_muc_odbc_async_pool_writer, []},
   {mod_mam_muc, [{host, "muclight.@HOST@"}]}
```

Then I request the Message History as following when i have created my group as receiver participant and to fetch old messages 


2) IQ for MAM , Note that the "from" Id is required else you will get error in stanza request. 

```
<iq type="set" to="mygrp-2bf4a6cf@muclight.mydmain.org.com" from="+6500000000@mydmain.org.com" id="modarchive-22317496CE4C">
    <query
        xmlns="urn:xmpp:mam:1" queryid="queryId-1FF4671B-183F-4CEA-BF84-CAAA5BA3293A"/>
 </iq>

RECV: 
<message
    xmlns="jabber:client" from="mygrp-2bf4a6cf@muclight.mydmain.org.com" to="+6500000000@mydomain.org.com/9CFB18FAFE570BB51479695753824643">
    <result
        xmlns="urn:xmpp:mam:1" queryid="queryId-1FF4671B-183F-4CEA-BF84-CAAA5BA3293A" id="AGE6FBE9JP01">
        <forwarded
            xmlns="urn:xmpp:forward:0">
            <delay
                xmlns="urn:xmpp:delay" from="mygrp-2bf4a6cf@muclight.mydmain.org.com" stamp="2016-11-21T02:33:24Z"/>
                <message
                    xmlns="jabber:client" from="mygrp-2bf4a6cf@muclight.mydmain.org.com" to="" id="changesubject-DE6E4E16-2FCB-4CEE-B943-82D168A21234" type="groupchat">
                    <x
                        xmlns="urn:xmpp:muclight:0#configuration">
                        <prev-version>1479-695600-624752</prev-version>
                        <version>1479-695604-160771</version>
                        <subject>FAKE GROUP</subject>
                    </x>
                    <body/>
                </message>
            </forwarded>
        </result>
    </message>


<message
    xmlns="jabber:client" from="mygrp-2bf4a6cf@muclight.mydmain.org.com" to="+6500000000@mydmain.org.com/9CFB18FAFE570BB51479695753824643">
    <result
        xmlns="urn:xmpp:mam:1" queryid="queryId-1FF4671B-183F-4CEA-BF84-CAAA5BA3293A" id="AGE6FH8KHJ01">
        <forwarded
            xmlns="urn:xmpp:forward:0">
            <delay
                xmlns="urn:xmpp:delay" from="mygrp-2bf4a6cf@muclight.mydmain.org.com/+6500000000@mydmain.org.com" stamp="2016-11-21T02:33:48Z"/>
                <message
                    xmlns="jabber:client" from="mygrp-2bf4a6cf@muclight.mydmain.org.com/+6500000000@mydmain.org.com" to="" id="CNV-1072D127-D70E-4B1D-ACA8-7AC083C31F3B" type="groupchat">
                    <body>321</body>
                    <active
                        xmlns="http://jabber.org/protocol/chatstates"/>
                        <x
                            xmlns="http://jabber.org/protocol/muc#user">
                            <item affiliation="owner" jid="+6500000000@mydmain.org.com/FEC4E6004987CD6A1479695571931626" role="owner"/>
                        </x>
                    </message>
                </forwarded>
            </result>
        </message>

```

**Comment by vickydhas** [comment]
Okay But my only question is , There is no pagination support and hence everytime then user from group is gone offline , and comes online I cant use this MAM as it will fetch always from the 0th item which will be too much load to fetch data.

Is there any possibility to make this pagination based fetch for messages like MAM MUC XEP-0045

**Comment by Jethvasagar** [comment]
issue solved Thank you @ludwikbukowski make my day.

**Comment by Jethvasagar** [comment]
muclight mod_mam module config error

`2017-09-09 11:12:18.836 [warning] <0.315.0>@mod_mam:start:185 mod_mam is enabled without explicit archive_groupchats option value. It will default to `false` in one of future releases. Please check the mod_mam documentation for more details.
2017-09-09 11:12:18.861 [critical] <0.315.0>@gen_mod:start_module:135 Problem starting the module mod_mam_odbc_arch for host <<"localhost">>
 options: [{pm,true}]
 error: {case_clause,undefined}
[{mongoose_rdbms,db_engine,1,
                 [{file,"/home/prakash/mongooseIMData/MongooseIM/_build/prod/lib/ejabberd/src/rdbms/mongoose_rdbms.erl"},
                  {line,454}]},
 {mod_mam_odbc_arch,index_hint_sql,1,
                    [{file,"/home/prakash/mongooseIMData/MongooseIM/_build/prod/lib/ejabberd/src/mod_mam_odbc_arch.erl"},
                     {line,196}]},
 {mod_mam_odbc_arch,start,2,
                    [{file,"/home/prakash/mongooseIMData/MongooseIM/_build/prod/lib/ejabberd/src/mod_mam_odbc_arch.erl"},
                     {line,87}]},
 {gen_mod,start_module,3,
          [{file,"/home/prakash/mongooseIMData/MongooseIM/_build/prod/lib/ejabberd/src/gen_mod.erl"},
           {line,112}]},
 {lists,foreach,2,[{file,"lists.erl"},{line,1338}]},
 {ejabberd_app,start,2,
               [{file,"/home/prakash/mongooseIMData/MongooseIM/_build/prod/lib/ejabberd/src/ejabberd_app.erl"},
                {line,69}]},
 {application_master,start_it_old,4,
                     [{file,"application_master.erl"},{line,273}]}]
2017-09-09 11:12:18.861 [critical] <0.315.0>@gen_mod:start_module:140 ejabberd initialization was aborted because a module start failed.
The trace is [{mongoose_rdbms,db_engine,1,[{file,"/home/prakash/mongooseIMData/MongooseIM/_build/prod/lib/ejabberd/src/rdbms/mongoose_rdbms.erl"},{line,454}]},{mod_mam_odbc_arch,index_hint_sql,1,[{file,"/home/prakash/mongooseIMData/MongooseIM/_build/prod/lib/ejabberd/src/mod_mam_odbc_arch.erl"},{line,196}]},{mod_mam_odbc_arch,start,2,[{file,"/home/prakash/mongooseIMData/MongooseIM/_build/prod/lib/ejabberd/src/mod_mam_odbc_arch.erl"},{line,87}]},{gen_mod,start_module,3,[{file,"/home/prakash/mongooseIMData/MongooseIM/_build/prod/lib/ejabberd/src/gen_mod.erl"},{line,112}]},{lists,foreach,2,[{file,"lists.erl"},{line,1338}]},{ejabberd_app,start,2,[{file,"/home/prakash/mongooseIMData/MongooseIM/_build/prod/lib/ejabberd/src/ejabberd_app.erl"},{line,69}]},{application_master,start_it_old,4,[{file,"application_master.erl"},{line,273}]}].
`
