### ISSUE TITLE
MUC Light message custom attribute

### ISSUE THREAD

**Issue by ludwikbukowski** [esl/MongooseIM#961]
MongooseIM version: 36b777c994da6dec40aa23323971da6a3131c27d
Installed from: SOURCE
Erlang/OTP version: 18.0

I tried add my custom  attribute to groupchat message stanza sent directly to the room:

``` xml
<message
         id='hysf1v37'
         to='room_10@muclight.localhost'
         custom="value"
         type='groupchat'>
    <body>Harpier cries: 'tis time, 'tis time.</body>
</message>
```

Looks like MUC Light module gets rid of unknown attributes and receivers just got:

``` xml
<message from="room_10@muclight.localhost/user_13@localhost" type="groupchat" to="user_13@localhost" id="hysf1v37">
    <body>Harpier cries: 'tis time, 'tis time.</body>
</message>
```

It does not happen when message send in one-to-one chat neither in legacy MUC.

**Comment by fenek** [comment]
It's not a bug, it's a feature, because XMPP RFC specifies only 5 allowed attributes for `<message/>` element: `from, to, type, id, xml:lang`. Actually `xml:lang` is omitted, so in this case it's a bug... :)

I think it's a matter of question, if we want to be strict about core XMPP specification in public MongooseIM version, or not so much. Thoughts anyone?

**Comment by vickydhas** [comment]
In addition to this the. Can we add the custom child nodes inside message stanza rather than custom attribute. 

In my scenario I want to add custome <mediaItem> ... some internal xml noted for media elements ... </mediaitem> inside my message stanza next to body element. Will this be also removed automatically when receiver gets message.

**Comment by fenek** [comment]
No, all XML elements inside `<message>` are forwarded.

**Comment by vickydhas** [comment]
Okay so understand it's only attribute level restriction now node level
inside I can have my own xml node structure sent.
>
>
That's great coz I want to send the chat message but handle inside nodes to
let receipient know if it's media message or text only.

Thanks a lot.


-- 
Sent from my iPhone6+
