### ISSUE TITLE
Domain Error

### ISSUE THREAD

**Issue by jakeperry** [esl/MongooseIM#966]
MongooseIM version: since 2.0beta1
Installed from: source
Erlang/OTP version: 18.3
No matter what domain I use in vm.args unless it is localhost I get errors when I try and register a user for that domain.

Failed RPC connection to the node 'mongooseim@domain.com': nodedown

=ERROR REPORT==== 9-Sep-2016::01:04:35 ===
** System NOT running to use fully qualified hostnames **
** Hostname domain.com is illegal **

I have DNS already setup and configure and even changed the /etc/hostname and /etc/hosts to match the domain name I want to use.

**Comment by fenek** [comment]
Hi @jakeperry 

Erlang nodes can run in one of two modes: using short hostname and long hostname. The former are any domains that do not have any dots (including IPs) and the latter are the opposite. An example of short hostname is `ip-12-34-56-78` and long hostnames are `xmpp.domain.com`, `192.168.1.1` etc. In order to use long hostname, you have to not only set its name in `vm.args` but change the same line to begin with `-name`, not `-sname`.
