### ISSUE TITLE
Hooks improvements - step 1

### ISSUE THREAD

**Issue by michalwski** [esl/MongooseIM#980]
Following the internal discussion the first step to improve hooks is to:
1. Unify the `Accumulator` (`Val`) passed to `ejabberd_hooks:run_fold`. Currently it can be anything, let it be a map with meaningful fields.
2. Rewrite all hooks which are run by `ejabberd_hooks:run` to behave exactly like `run_fold` the `Accumulator` in this case should be an empty map. They can still be run by `ejabberd_hooks:run`.

**Comment by bartekgorny** [comment]
So, if I get it right, every handler func would look like:
`a_handler(#{} = V, Arg1...Argn) -> #{}`
and if we fold we pass the map from handler to handler, if we run we just give each handler an empty map. Then we retrieve return value of a fold from a map, so it'll be sthg like:
`NewMap = mongoose_hooks:run_fold(some_hook, OldMap, [Arg1...Argn])`
or
`ok = mongoose_hooks:run(some_hook, [Arg1...Argn])`

Is it what you mean?

**Comment by michalwski** [comment]
>  if we run we just give each handler an empty map.
No, what I mean, the initial value is empty map, the first handler gets empty map, any other subsequent handler should get what the previous returns, just like in fold.

**Comment by bartekgorny** [comment]
Thus: `NewMap = mongoose_hooks:run(some_hook, [Arg1...Argn])`

**Comment by michalwski** [comment]
Correct :)

**Comment by erszcz** [comment]
:+1:

**Comment by bartekgorny** [comment]
Pushing that logic a bit further - if we are determined to go through all handlers, 
then perhaps we could venture to unify handlers' interfaces? Currently a scope of 
args passed to hook:run/run_fold varies, which causes problems like: "I'd like 
to add a handler doing certain thing, but what I need is not in Args, so I have 
to edit the hook call AND all handlers attached to it". Since a set of
arguments which are available to hook calls and could be used by handlers is limited
(host, stanza, jid from, jid to, session, and a few occasional things), we could make
Args a record and make each call to hooks stuff whatever is available at this stage
into it and use it instead of Args vector. And the accumulator can, as agreed, be 
a map with some initial value (fold) or empty (run), with handlers putting into it
whatever they like, and the function that call the hook using it at its discretion
and then discarding it.

This has three advantages:
1. Solves the problem of new handlers which need additional args
2. Prevents using accumulator as carrier of ad-hoc arguments
3. Paves the way for further development, which probably will be making some data
structure flow through the whole processing chain, and it will probably be our future Args
