### ISSUE TITLE
MUC Light documentation details

### ISSUE THREAD

**Issue by erszcz** [esl/MongooseIM#997]
From [MUC Light 8.1.8. Blocking functionality](http://mongooseim.readthedocs.io/en/latest/open-extensions/muc_light/#45-blocking-functionality):

> [...] Stanzas MUST be addressed to the server JID. The privacy list name MUST be equal to "urn:xmpp:muclight:0". Obviously, this method won't work properly in XMPP Server Federation. [...]

How will it work then? What will not work and why? Is this remark just pointing to the fact that non-MongooseIM servers don't support MUC Light or is there more to it?

**Comment by fenek** [comment]
Since the "legacy" blocking functionality is based on classic privacy lists, which are handled locally, the information won't be forwarded to a MUC Light service running on a federated host. MUC Light blocking is not based on stanza drop but processed by the service.

BTW: There is a mistake here :( because default `to` is user's bare JID, not server JID.
